In [1]:
import pandas as pd

df = pd.read_csv(
    "../raw/Vittime.stato_civile.csv",
    sep=",",
    quotechar="'",
    encoding="utf-8-sig"
)

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,MARITAL_STATUS,Stato civile,TIME_PERIOD,Osservazione,OBS_STATUS,Stato_osservazione
0,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,SIN,Celibe/nubile,2015,130,NaN,NaN
1,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,SIN,Celibe/nubile,2016,141,NaN,NaN
2,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,SIN,Celibe/nubile,2017,129,NaN,NaN
3,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,SIN,Celibe/nubile,2018,109,NaN,NaN
4,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,SIN,Celibe/nubile,2019,93,NaN,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 2
Valori unici:
['A' '"A']


============================================================
Colonna: Frequenza
Numero valori unici: 1
Valori unici:
['Annuale']


============================================================
Colonna: REF_AREA
Numero valori unici: 29
Valori unici:
['IT' 'ITC' 'ITC1' 'ITC2' 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2' 'ITNI']


============================================================
Colonna: Territorio
Numero valori unici: 29
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' 'Valle d""Aosta / Vallée d""\'Aoste\''
 'Liguria' 'Lombardia' 'Nord-est' 'Trentino Alto Adige / Südtirol'
 'Provincia Autonoma Bolzano / Bozen' 'Provincia Autonoma Trento' 'Veneto'
 'Friuli-Venezia Giulia' 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria'
 'Marche' 'Lazio' 'Sud' 'Abruzzo' 'Molise' 'Campania' 'Puglia'
 'Basilicata' 'Calabria' 'Isole' 'Sicilia' 'Sardegna' 'Non indicato']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 1
Valori unici:
['VICTIMS']


============================================================
Colonna: Indicatore
Numero valori unici: 1
Valori unici:
['Vittime di violenza']


============================================================
Colonna: SEX
Numero valori unici: 4
Valori unici:
['M' 'F' 'NRP' 'T']


============================================================
Colonna: Sesso
Numero valori unici: 4
Valori unici:
['Maschi' 'Femmine' 'Non indicato' 'Totale']


============================================================
Colonna: MARITAL_STATUS
Numero valori unici: 8
Valori unici:
['SIN' 'SEP_FSEP' 'MAR2' 'DIV2' 'WID2' 'NRP' 'UNAV' 'ALL']


============================================================
Colonna: Stato civile
Numero valori unici: 8
Valori unici:
['Celibe/nubile' 'Separato di fatto/legalmente da matrimonio'
 'Coniugato, unito civilmente, separato da matrimonio/unione civile'
 'Divorziato da matrimonio/unione civile'
 'Vedovo da matrimonio/unione civile' 'Non indicato' 'Non disponibile'
 'Totale']


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 10
Valori unici:
[2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]


============================================================
Colonna: Osservazione
Numero valori unici: 932
Valori unici:
[  130   141   129   109    93   250   263   208   243    40    24    30
    18    10    28    25    14    27    90    98    66    74   145   103
    44   115   112     6    12     9    13     8     7     5     4    11
     2    15     3     1    83    26    58    32    33    21    41    54
   311   295   286   261   218   571   540   262   425   433  2235  2364
  2449  2918  2977  5318  6157  4630  6261  7394   824   849   822   926
   843  1217  1174   923  1218  1356  3674  3648  3457  4254  3496  5908
  5428  3926  4906  5590   307   337   396   459   404   481   417   394
   564   669   298   278   289   237   480   450   326   350   392    51
    73    71    60    38  1062  1308   554  1112   689   381   281   341
   435   432   662   786   879  7770  7830  7799  9341  8427 15128 15720
 11632 14455 16117    46  1292  1014  1403  1081  2365  2505  2578  3027
  3070  5568  6420  4771  6502  7655   864   873   852   944   853  1245
  1199   937  1248  1387  3764  3746  3523  4347  3570  6053  5531  3970
  5049  5717   313   343   408   468   414   494   401   573   682   308
   283   270   297   241   491   463   330   358   398    53    80    86
    63    39  1145  1382   580  1216   751   415   368   456   460   712
   920  8082  8125  8085  9602  8647 15708 16272 11909 16283 17631    29
    42    55    56    22    35    20    72    64    61   102    96   625
   727   688   788  1476  1274  1525  2066   234   225   310   229   301
   379   927  1028   908  1009   841  1420  1261   951  1130  1429   107
   113   133   134   126    95   162   193    85    91    62   120    75
   100    17    16   176   268   101   191   168    52    57  2077  2213
  2075  2320  2159  3572  3532  2794  3384  4335    50    70   654   759
   714   816   846  1398  1531  1301  1588  2122   253   235   227   226
   236   318   309   386   953  1057   929  1033   863  1455  1281   966
  1158   110   117   136   137   166   197    89   121    76   185   104
   203   174    59    68    47  2149  2277  2146  2381  2215  3635  2845
  3550  4475    19    36   179   207   198   209   224   399   335   402
   471    78    81    69    97    65   339   320   342   266   376    43
    45    37    23   645   684   623   709   632   985   952   747   911
  1076   188   216   214   348   416   340   489    79    99   116   296
   271   327   276   411   269   325   384    34    31   703   651   722
   647  1011   988   948    82    67   128   122   123   108    77   127
   205   183   228   184   231   360   118   171    94   212   215   189
   322   319   277   370   378   419   504   521   902   945   826   999
  1419   138   132   161   139   202   230   544   608   562   585   505
   886   810   732   917    49   106   125  1215  1309  1260  1374  1334
  2263  2264  1802  2204  2877   393   451   434   525   539   977  1042
  1453   147   163   556   626   572   597   519   619   753   933    87
   135  1256  1348  1297  1415  1370  2324  2322  1835  2318  2969   302
   303   317   409   457   744   958   711   974   124   172   244   443
   438   565   499   803   825   646   728  1024    48   131   157    84
   167  1026   975  1255  1196  2005  2278  1702  2175  3012   321   323
   421   782   986   734  1008  1484   111   177   252   524   453   578
   514   842  1039  1075  1048  1286  1228  2083  2339  1731  2271  3114
   140   150   146   154   158   186   361   410   653   240   210   285
   264   389   353   492   475   614   611   956  1141   861  1393   142
   194   493   346   426   670   114   249   219   211   291   354   397
   486   490   992  1169   871  1056  1436   169   119   173   175   187
   190   328   312   422   589   178   347   329   247   403   437   423
   513   479   882   965   710  1208   156   600   217   357   338   257
   413   522   913   994   894   549   742   756  1193  1384  1137  1408
  1713   774   762   757  1126  1128   963  1189   105    92   148   165
  1715  1678  1570  2096  1941  3053  3385  2573  3062  3573   561   766
   781  1271  1435  1182  1452  1770   213   300   789   787   655   885
   770  1156  1146  1212   153   282  1771  1754  1633  2153  1989  3183
  3487  2643  3213  3724   143   149   222   196   204   427   559   516
   829   827   616   724   995   363   332   496   314   206   344   869
   858   638  1034   144   200   220   181   256   267   221   279   374
   445   845   699   883   957   159   170   447   429   667   462   569
  1058   872  1195  1797  2044  1552  1875   355   400   316   431   467
   723   151   465   334   502   649   678   466   584  1045  1101   905
  1232  1869  2104  1587  1975  2092   570   939  1102   778   876  1122
   233  1083   875  1326  1230   925   972  1172  1810  1710  1541  2037
  1806  2882  3005  2196  2377  2837   455   590   973  1144   795   898
  1170   199   238   779  1103   892  1355  1252   935   998  1200  1883
  1776  1593  2099  1849  2964  3089  2234  2481   290   272   258   299
   239   275   255   351   483   441   509   594   579   458   575   874
   830   960  1295  1372   968  1287   223   488   452   603   588   904
   862   745   990  1323  1407   991  1345   372   364   248   495   448
   464   820   635   889   152   352   273   251   428   642   706    88
   324   245   359   274   377   349   362   336   721   777   784   700
  1117  1197  1088   367   365   485   406   802   740   807   716  1159
   315   331   254   260   555   515   583   652   785   155   284   304
   815   888   596   819   232   242   265   665  1152   577   713   382
   180   373   388   887  2395  2172  1405  2575  1272  1121   698   164
   201   696   930  2531  2326  1475  3848  2219]


============================================================
Colonna: OBS_STATUS
Numero valori unici: 1
Valori unici:
[nan]


============================================================
Colonna: Stato_osservazione
Numero valori unici: 2
Valori unici:
[nan '"']

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",         
    "SEX",                
    "MARITAL_STATUS",     
    "OBS_STATUS",         
    "Stato_osservazione" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (5792, 5)
Colonne rimanenti: ['Territorio', 'Sesso', 'Stato civile', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Stato civile": "stato_civile",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Valle d""Aosta / Vallée d""\'Aoste\''
 'Liguria' 'Lombardia' 'Nord-est' 'Trentino Alto Adige / Südtirol'
 'Provincia Autonoma Bolzano / Bozen' 'Provincia Autonoma Trento' 'Veneto'
 'Friuli-Venezia Giulia' 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria'
 'Marche' 'Lazio' 'Sud' 'Abruzzo' 'Molise' 'Campania' 'Puglia'
 'Basilicata' 'Calabria' 'Isole' 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: stato_civile
['Celibe/nubile' 'Separato di fatto/legalmente da matrimonio'
 'Coniugato, unito civilmente, separato da matrimonio/unione civile'
 'Divorziato da matrimonio/unione civile'
 'Vedovo da matrimonio/unione civile' 'Non indicato' 'Non disponibile'
 'Totale']

Colonna: periodo
[2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]

Colonna: numero_vittime
[  130   141   129   109    93   250   263   208   243    40    24    30
    18    10    28    25    14    27    90    98    66    74   145   103
    44   115   112     6    12     9    13     8     7     5     4    11
     2    15     3     1    83    26    58    32    33    21    41    54
   311   295   286   261   218   571   540   262   425   433  2235  2364
  2449  2918  2977  5318  6157  4630  6261  7394   824   849   822   926
   843  1217  1174   923  1218  1356  3674  3648  3457  4254  3496  5908
  5428  3926  4906  5590   307   337   396   459   404   481   417   394
   564   669   298   278   289   237   480   450   326   350   392    51
    73    71    60    38  1062  1308   554  1112   689   381   281   341
   435   432   662   786   879  7770  7830  7799  9341  8427 15128 15720
 11632 14455 16117    46  1292  1014  1403  1081  2365  2505  2578  3027
  3070  5568  6420  4771  6502  7655   864   873   852   944   853  1245
  1199   937  1248  1387  3764  3746  3523  4347  3570  6053  5531  3970
  5049  5717   313   343   408   468   414   494   401   573   682   308
   283   270   297   241   491   463   330   358   398    53    80    86
    63    39  1145  1382   580  1216   751   415   368   456   460   712
   920  8082  8125  8085  9602  8647 15708 16272 11909 16283 17631    29
    42    55    56    22    35    20    72    64    61   102    96   625
   727   688   788  1476  1274  1525  2066   234   225   310   229   301
   379   927  1028   908  1009   841  1420  1261   951  1130  1429   107
   113   133   134   126    95   162   193    85    91    62   120    75
   100    17    16   176   268   101   191   168    52    57  2077  2213
  2075  2320  2159  3572  3532  2794  3384  4335    50    70   654   759
   714   816   846  1398  1531  1301  1588  2122   253   235   227   226
   236   318   309   386   953  1057   929  1033   863  1455  1281   966
  1158   110   117   136   137   166   197    89   121    76   185   104
   203   174    59    68    47  2149  2277  2146  2381  2215  3635  2845
  3550  4475    19    36   179   207   198   209   224   399   335   402
   471    78    81    69    97    65   339   320   342   266   376    43
    45    37    23   645   684   623   709   632   985   952   747   911
  1076   188   216   214   348   416   340   489    79    99   116   296
   271   327   276   411   269   325   384    34    31   703   651   722
   647  1011   988   948    82    67   128   122   123   108    77   127
   205   183   228   184   231   360   118   171    94   212   215   189
   322   319   277   370   378   419   504   521   902   945   826   999
  1419   138   132   161   139   202   230   544   608   562   585   505
   886   810   732   917    49   106   125  1215  1309  1260  1374  1334
  2263  2264  1802  2204  2877   393   451   434   525   539   977  1042
  1453   147   163   556   626   572   597   519   619   753   933    87
   135  1256  1348  1297  1415  1370  2324  2322  1835  2318  2969   302
   303   317   409   457   744   958   711   974   124   172   244   443
   438   565   499   803   825   646   728  1024    48   131   157    84
   167  1026   975  1255  1196  2005  2278  1702  2175  3012   321   323
   421   782   986   734  1008  1484   111   177   252   524   453   578
   514   842  1039  1075  1048  1286  1228  2083  2339  1731  2271  3114
   140   150   146   154   158   186   361   410   653   240   210   285
   264   389   353   492   475   614   611   956  1141   861  1393   142
   194   493   346   426   670   114   249   219   211   291   354   397
   486   490   992  1169   871  1056  1436   169   119   173   175   187
   190   328   312   422   589   178   347   329   247   403   437   423
   513   479   882   965   710  1208   156   600   217   357   338   257
   413   522   913   994   894   549   742   756  1193  1384  1137  1408
  1713   774   762   757  1126  1128   963  1189   105    92   148   165
  1715  1678  1570  2096  1941  3053  3385  2573  3062  3573   561   766
   781  1271  1435  1182  1452  1770   213   300   789   787   655   885
   770  1156  1146  1212   153   282  1771  1754  1633  2153  1989  3183
  3487  2643  3213  3724   143   149   222   196   204   427   559   516
   829   827   616   724   995   363   332   496   314   206   344   869
   858   638  1034   144   200   220   181   256   267   221   279   374
   445   845   699   883   957   159   170   447   429   667   462   569
  1058   872  1195  1797  2044  1552  1875   355   400   316   431   467
   723   151   465   334   502   649   678   466   584  1045  1101   905
  1232  1869  2104  1587  1975  2092   570   939  1102   778   876  1122
   233  1083   875  1326  1230   925   972  1172  1810  1710  1541  2037
  1806  2882  3005  2196  2377  2837   455   590   973  1144   795   898
  1170   199   238   779  1103   892  1355  1252   935   998  1200  1883
  1776  1593  2099  1849  2964  3089  2234  2481   290   272   258   299
   239   275   255   351   483   441   509   594   579   458   575   874
   830   960  1295  1372   968  1287   223   488   452   603   588   904
   862   745   990  1323  1407   991  1345   372   364   248   495   448
   464   820   635   889   152   352   273   251   428   642   706    88
   324   245   359   274   377   349   362   336   721   777   784   700
  1117  1197  1088   367   365   485   406   802   740   807   716  1159
   315   331   254   260   555   515   583   652   785   155   284   304
   815   888   596   819   232   242   265   665  1152   577   713   382
   180   373   388   887  2395  2172  1405  2575  1272  1121   698   164
   201   696   930  2531  2326  1475  3848  2219]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)


df["territorio"] = df["territorio"].replace({
    'valle d""aosta / vallée d""\'aoste\'': "valle d'aosta",
    "trentino alto adige / südtirol": "trentino alto adige",
    "provincia autonoma bolzano / bozen": "bolzano",
    "provincia autonoma trento": "trento"
})


# Uniformazione minuscolo per la colonna sesso e stato_civile
df["sesso"] = df["sesso"].str.lower().str.strip()
df["stato_civile"] = df["stato_civile"].str.lower().str.strip()


# Rimozione della voce aggregata "totale" 
# da sesso e stato_civile per evitare doppio conteggio

df = df[
    (df["sesso"] != "totale") &
    (df["stato_civile"] != "totale")
]


# Modifica denominazioni verbose e non inclusive per la colonna stato_civile
df["stato_civile"] = df["stato_civile"].replace({
    "celibe/nubile": "single",
    "separato di fatto/legalmente da matrimonio": "separat",
    "coniugato, unito civilmente, separato da matrimonio/unione civile": "coniugat",
    "divorziato da matrimonio/unione civile": "divorziat",
    "vedovo da matrimonio/unione civile": "vedov",
    "non indicato": "non indicato",
    "non disponibile": "non disponibile"
})


# Conversione delle colonne numeriche da float a integer

df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)


# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

  territorio   sesso stato_civile  periodo  numero_vittime
0     italia  maschi       single     2015             130
1     italia  maschi       single     2016             141
2     italia  maschi       single     2017             129
3     italia  maschi       single     2018             109
4     italia  maschi       single     2019              93
5     italia  maschi       single     2020             250
6     italia  maschi       single     2021             263
7     italia  maschi       single     2022             141
8     italia  maschi       single     2023             208
9     italia  maschi       single     2024             243

<class 'pandas.core.frame.DataFrame'>
Index: 3062 entries, 0 to 5704
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   territorio      3062 non-null   object
 1   sesso           3062 non-null   object
 2   stato_civile    3062 non-null   object
 3   periodo         3062 non-null   int64
 4   numero_vittime  3062 non-null   int64
dtypes: int64(2), object(3)
memory usage: 143.5+ KB

Missing values per colonna:

territorio        0
sesso             0
stato_civile      0
periodo           0
numero_vittime    0
dtype: int64

Numero valori unici per colonna:

numero_vittime    476
territorio         29
periodo            10
stato_civile        7
sesso               3
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' "valle d'aosta" 'liguria' 'lombardia'
 'nord est' 'trentino alto adige' 'bolzano' 'trento' 'veneto'
 'friuli venezia giulia' 'emilia romagna' 'centro' 'toscana' 'umbria'
 'marche' 'lazio' 'sud' 'abruzzo' 'molise' 'campania' 'puglia'
 'basilicata' 'calabria' 'isole' 'sicilia' 'sardegna' 'non indicato']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: stato_civile
['single' 'separat' 'coniugat' 'divorziat' 'vedov' 'non indicato'
 'non disponibile']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[ 130  141  129  109   93  250  263  208  243   40   24   30   18   10
   28   25   14   27   90   98   66   74  145  103   44  115  112    6
   12    9   13    8    7    5    4   11    2   15    3    1   83   26
   58   32   33   21   41   54 2235 2364 2449 2918 2977 5318 6157 4630
 6261 7394  824  849  822  926  843 1217 1174  923 1218 1356 3674 3648
 3457 4254 3496 5908 5428 3926 4906 5590  307  337  396  459  404  481
  417  394  564  669  298  278  289  237  480  450  326  350  392   51
   73   71   60   38 1062 1308  554 1112  689  381  281  341  435  432
  662  786  879   46 1292 1014   29   42   55   56   53   22   35   20
  625  727  688  788 1476 1274 1525 2066  234  218  225  310  295  229
  301  379  927 1028  908 1009  841 1420 1261  951 1130 1429  107  113
  133  134  126   95  162  193   85   91   62  120   86   75  100   17
   16  176  268  101  191  168   52   57   64   50   39  179  207  198
  209  224  399  335  402  471   78   76   81   69   97   65  283  339
  320  270  401  342  266  376   36   43   47   45   37   23   82   67
   72  128  104  122   34   80   61  123  108   77  127   19  378  419
  504  521  902  945  826  999 1419  138  132  121  161  139  202  230
  544  608  562  585  505  886  810  732  917   63   79   70   49   59
  106  185  125  116  302  303  317  409  457  744  958  711  974 1453
   96  135  124  172  163  174  244  443  438  565  499  803  825  646
  728 1024   48  131   31  157   84  167  117  158  186  361  410  653
  240  216  210  285  264  389  353  386  492   68  140  187  190  328
  312  422  589   89  178  184  347  329  247  403  549  524  742  756
 1193 1384 1137 1408 1713  183  214  262  236  286  774  762  645  864
  757 1126 1128  816  963 1189  105   92  114  148  118   99  165  269
  194  143  205  346  261  325  149  222  196  309  282  204  321  110
   87  374  414  445  703  845  699  883  957  102  159  170  447  456
  327  490  429  632  667  462  569  479  463  434  539  570  939 1102
  778  876 1122  189  175  233  226  873 1083  875 1326 1230  925  972
 1172  119  213  211  255  253  351  468  483  441  509  431  594  579
  426  458  575  276  338  372  241  221  364  248  340  111  181  199
  219  215  377  452  357  349  362  363  344  322  475  455  336  146
  150  144  315  331  279  254  291  343  260  297  137  252  665  721
 1152  577  156  169  713  785  384  284  382  136  180  197 1121  827]

In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/vittime.stato_civile.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/vittime.stato_civile.csv