In [1]:
import pandas as pd

df = pd.read_csv("../raw/Vittime.stato_denuncia.csv")

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,COMP_REASWITHDRAWAL,Denucia_motivo_ritiro,TIME_PERIOD,Osservazione,OBS_STATUS,Stato_osservazione
0,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,REPORT,Denuncia,2015.0,37.0,NaN,NaN
1,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,REPORT,Denuncia,2016.0,38.0,NaN,NaN
2,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,REPORT,Denuncia,2017.0,34.0,NaN,NaN
3,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,REPORT,Denuncia,2018.0,30.0,NaN,NaN
4,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,REPORT,Denuncia,2019.0,19.0,NaN,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 85
Valori unici:
['A'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,NOREPORT,Non denuncia,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,NOREPORT,Non denuncia,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,NOREPORT,Non denuncia,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,NOREPORT,Non denuncia,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,NRP,Non risponde,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,UNAV,Non disponibile,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2015,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2019,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2022,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT,Denuncia,2024,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,WITHDR_COMP,Ritira la denuncia,2019,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2015,8,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2016,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2017,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2018,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2019,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2020,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2021,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2022,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2023,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NOREPORT,Non denuncia,2024,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2019,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2020,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2017,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2018,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2022,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2023,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2024,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,UNAV,Non disponibile,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,ALL,Tutte le voci,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2015,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2019,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2022,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT,Denuncia,2024,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,WITHDR_COMP,Ritira la denuncia,2019,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2015,8,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2016,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2017,8,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2018,8,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2019,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2020,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2021,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2022,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2023,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NOREPORT,Non denuncia,2024,18,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NRP,Non risponde,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2019,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2020,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2017,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2018,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2022,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2023,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2024,24,,']


============================================================
Colonna: Frequenza
Numero valori unici: 2
Valori unici:
['Annuale' nan]


============================================================
Colonna: REF_AREA
Numero valori unici: 29
Valori unici:
['IT' 'ITC' 'ITC1' nan 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2' 'ITNI']


============================================================
Colonna: Territorio
Numero valori unici: 29
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' nan 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 2
Valori unici:
['VICTIMS' nan]


============================================================
Colonna: Indicatore
Numero valori unici: 2
Valori unici:
['Vittime di violenza' nan]


============================================================
Colonna: SEX
Numero valori unici: 5
Valori unici:
['M' 'F' 'NRP' 'T' nan]


============================================================
Colonna: Sesso
Numero valori unici: 5
Valori unici:
['Maschi' 'Femmine' 'Non indicato' 'Totale' nan]


============================================================
Colonna: COMP_REASWITHDRAWAL
Numero valori unici: 7
Valori unici:
['REPORT' 'WITHDR_COMP' 'NOREPORT' 'NRP' 'UNAV' 'ALL' nan]


============================================================
Colonna: Denucia_motivo_ritiro
Numero valori unici: 7
Valori unici:
['Denuncia' 'Ritira la denuncia' 'Non denuncia' 'Non risponde'
 'Non disponibile' 'Tutte le voci' nan]


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 11
Valori unici:
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.   nan]


============================================================
Colonna: Osservazione
Numero valori unici: 927
Valori unici:
[3.7000e+01 3.8000e+01 3.4000e+01 3.0000e+01 1.9000e+01 4.3000e+01
 6.9000e+01 2.2000e+01 4.7000e+01 4.4000e+01 3.0000e+00 1.1000e+01
 4.0000e+00 9.0000e+00 7.0000e+00 1.0000e+00 2.1000e+02 2.1100e+02
 1.8300e+02 1.7900e+02 1.6000e+02 3.0300e+02 2.8800e+02 1.8200e+02
 3.1200e+02 3.3100e+02 2.0000e+00 5.0000e+00 5.5000e+01 3.6000e+01
 6.0000e+01 3.3000e+01 6.4000e+01 2.1200e+02 1.7100e+02 1.5000e+01
 3.1100e+02 2.9500e+02 2.8600e+02 2.6100e+02 2.1800e+02 5.7100e+02
 5.4000e+02 2.6200e+02 4.2500e+02 4.3300e+02 1.0980e+03 1.1770e+03
 1.1500e+03 1.3330e+03 1.2910e+03 1.6100e+03 2.1150e+03 1.5000e+03
 1.9700e+03 1.9920e+03 2.9300e+02 3.4100e+02 2.5600e+02 2.7900e+02
 3.7600e+02 3.1800e+02 2.8100e+02 4.6500e+02 5.7100e+03 5.7280e+03
 5.5350e+03 6.6970e+03 6.0810e+03 8.9580e+03 9.9070e+03 8.0560e+03
 1.0322e+04 1.2319e+04 3.9000e+01 4.5000e+01 3.5000e+01 2.7000e+01
 1.2100e+02 2.2100e+02 2.0600e+02 1.5350e+03 9.2600e+02 6.2200e+02
 5.4500e+02 8.1300e+02 9.9000e+02 7.4900e+02 4.1510e+03 3.1010e+03
 1.5520e+03 3.4700e+02 4.1500e+02 7.7700e+03 7.8300e+03 7.7990e+03
 9.3410e+03 8.4270e+03 1.5128e+04 1.5720e+04 1.1632e+04 1.4455e+04
 1.6117e+04 2.0000e+01 6.0000e+00 2.9000e+01 3.1000e+01 5.7000e+01
 2.3000e+01 1.2000e+01 1.2960e+03 1.0210e+03 1.4030e+03 1.0810e+03
 1.1350e+03 1.2150e+03 1.1840e+03 1.3630e+03 1.3100e+03 1.6530e+03
 2.1840e+03 1.5220e+03 2.0370e+03 2.0420e+03 2.9600e+02 3.5200e+02
 2.5900e+02 2.9000e+02 2.8200e+02 2.9700e+02 3.8300e+02 3.1900e+02
 4.7200e+02 5.9200e+03 5.9390e+03 5.7180e+03 6.8760e+03 6.2410e+03
 9.2610e+03 1.0195e+04 8.2380e+03 1.0663e+04 1.2681e+04 4.8000e+01
 4.1000e+01 1.2500e+02 2.2600e+02 2.0800e+02 1.6470e+03 9.8500e+02
 6.8300e+02 5.7800e+02 8.7700e+02 1.0370e+03 7.8500e+02 4.3720e+03
 3.2840e+03 1.6220e+03 1.6500e+03 1.4510e+03 8.0820e+03 8.1250e+03
 8.0850e+03 9.6020e+03 8.6470e+03 1.5708e+04 1.6272e+04 1.1909e+04
 1.6283e+04 1.7631e+04 8.0000e+00 1.0000e+01 5.9000e+01 5.0000e+01
 4.2000e+01 6.6000e+01 7.6000e+01 6.7000e+01 1.3000e+01 2.4000e+01
 7.2000e+01 7.1000e+01 6.1000e+01 5.6000e+01 1.0200e+02 1.0300e+02
 5.1000e+01 9.6000e+01 9.0000e+01 3.0000e+02 3.4600e+02 2.7800e+02
 3.2200e+02 4.1400e+02 4.9600e+02 3.5600e+02 4.4700e+02 5.1000e+02
 8.5000e+01 8.0000e+01 7.4000e+01 7.5000e+01 1.1700e+02 8.3000e+01
 1.2200e+02 1.5660e+03 1.6750e+03 1.5410e+03 1.7130e+03 1.6430e+03
 2.3170e+03 2.4020e+03 2.1570e+03 2.5390e+03 3.3870e+03 2.1000e+01
 4.6000e+01 2.4100e+02 1.3100e+02 9.4000e+01 1.6300e+02 1.8700e+02
 7.4500e+02 4.7100e+02 2.0770e+03 2.2130e+03 2.0750e+03 2.3200e+03
 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03 3.3840e+03 4.3350e+03
 7.0000e+01 3.0500e+02 3.5400e+02 2.8500e+02 3.4500e+02 3.2700e+02
 4.2400e+02 5.1100e+02 3.5800e+02 4.6200e+02 5.2000e+02 8.8000e+01
 6.5000e+01 7.7000e+01 1.1900e+02 8.4000e+01 1.2300e+02 1.6250e+03
 1.7230e+03 1.5910e+03 1.7600e+03 1.6850e+03 2.3830e+03 2.4610e+03
 2.1940e+03 2.6230e+03 3.4580e+03 1.4000e+01 1.6000e+01 2.5700e+02
 1.3800e+02 9.9000e+01 1.7600e+02 1.9500e+02 1.2400e+02 7.6900e+02
 4.9800e+02 1.7000e+02 9.3000e+01 2.1490e+03 2.2770e+03 2.1460e+03
 2.3810e+03 2.2150e+03 3.6740e+03 3.6350e+03 2.8450e+03 3.5500e+03
 4.4750e+03 1.8000e+01 2.8000e+01 2.6000e+01 8.2000e+01 1.0900e+02
 9.8000e+01 1.1800e+02 1.5400e+02 1.0000e+02 1.1200e+02 2.5000e+01
 1.7000e+01 4.9400e+02 4.6400e+02 5.2700e+02 4.7500e+02 6.3300e+02
 6.3100e+02 5.8300e+02 6.7100e+02 8.3900e+02 9.1000e+01 1.2000e+02
 6.4500e+02 6.8400e+02 6.2300e+02 7.0900e+02 6.3200e+02 9.5200e+02
 7.4700e+02 9.1100e+02 1.0760e+03 1.0600e+02 1.0100e+02 1.5900e+02
 3.2000e+01 5.1500e+02 5.3300e+02 4.8200e+02 5.3700e+02 4.8600e+02
 6.5200e+02 6.5000e+02 5.9200e+02 6.8600e+02 8.6100e+02 5.8000e+01
 2.1300e+02 1.3200e+02 6.6900e+02 7.0300e+02 6.5100e+02 7.2200e+02
 6.4700e+02 1.0110e+03 9.8800e+02 7.5900e+02 9.4800e+02 1.1120e+03
        nan 1.5700e+02 1.4600e+02 1.5100e+02 2.1700e+02 2.0900e+02
 1.8100e+02 2.7700e+02 5.4000e+01 5.2000e+01 2.0500e+02 2.2800e+02
 1.8400e+02 3.0700e+02 3.1000e+02 2.3100e+02 2.6300e+02 3.6000e+02
 1.6200e+02 1.6600e+02 1.5500e+02 2.2300e+02 2.1400e+02 6.2000e+01
 2.1500e+02 1.8800e+02 2.3400e+02 1.8900e+02 2.3500e+02 3.7000e+02
 4.0000e+01 1.8000e+02 2.0100e+02 2.6700e+02 3.0200e+02 3.4800e+02
 4.9000e+01 7.8000e+01 9.0700e+02 9.2400e+02 1.0190e+03 1.4570e+03
 1.5570e+03 1.3830e+03 2.2540e+03 1.4700e+02 5.3000e+01 2.9900e+02
 1.0800e+02 1.3090e+03 1.2600e+03 1.3740e+03 1.3340e+03 2.2630e+03
 2.2640e+03 1.8020e+03 2.2040e+03 2.8770e+03 1.9200e+02 2.0300e+02
 2.7300e+02 3.1300e+02 3.5700e+02 7.9000e+01 9.3900e+02 1.0180e+03
 9.5000e+02 1.0490e+03 1.0380e+03 1.4980e+03 1.5920e+03 1.4070e+03
 1.7100e+03 2.2980e+03 1.2900e+02 4.8800e+02 1.1400e+02 1.2560e+03
 1.3480e+03 1.2970e+03 1.4150e+03 1.3700e+03 2.3240e+03 2.3220e+03
 1.8350e+03 2.3180e+03 2.9690e+03 1.2700e+02 1.5800e+02 2.5000e+02
 3.6900e+02 8.0300e+02 7.7800e+02 7.4800e+02 9.5800e+02 8.5900e+02
 1.3070e+03 1.5640e+03 1.2760e+03 2.3550e+03 1.5200e+02 6.3000e+01
 1.0500e+02 4.3400e+02 3.4000e+02 1.0260e+03 1.0090e+03 9.7500e+02
 1.2550e+03 1.1960e+03 2.0050e+03 2.2780e+03 1.7020e+03 2.1750e+03
 3.0120e+03 1.3700e+02 1.9100e+02 2.5100e+02 9.2000e+01 8.0600e+02
 7.7200e+02 9.7900e+02 8.8400e+02 1.3560e+03 1.6000e+03 1.3000e+03
 1.6650e+03 2.4060e+03 2.0400e+02 1.0700e+02 4.5700e+02 1.0750e+03
 1.0480e+03 1.2860e+03 1.2280e+03 2.0830e+03 2.3390e+03 1.7310e+03
 2.2710e+03 3.1140e+03 1.1000e+02 1.1500e+02 1.4000e+02 1.5000e+02
 1.1300e+02 6.8000e+01 1.1100e+02 1.3500e+02 3.6500e+02 4.4800e+02
 4.3700e+02 6.0600e+02 7.7100e+02 6.3400e+02 7.4300e+02 1.0630e+03
 1.6700e+02 4.8000e+02 4.6800e+02 6.1400e+02 6.1100e+02 9.5600e+02
 1.1410e+03 1.0140e+03 1.3930e+03 1.7700e+02 3.9500e+02 4.6300e+02
 4.4900e+02 6.2900e+02 7.8700e+02 6.4400e+02 7.6200e+02 1.0840e+03
 7.3000e+01 2.2400e+02 1.7300e+02 5.0400e+02 4.9000e+02 6.2600e+02
 9.9200e+02 1.1690e+03 8.7100e+02 1.0560e+03 1.4360e+03 8.7000e+01
 8.1000e+01 1.0400e+02 1.3600e+02 1.2800e+02 1.6100e+02 1.6900e+02
 1.3000e+02 1.6800e+02 8.9000e+01 1.1600e+02 1.7500e+02 2.6900e+02
 1.3900e+02 3.5000e+02 3.9700e+02 5.9000e+02 6.8900e+02 5.4100e+02
 9.6300e+02 1.7800e+02 4.2300e+02 3.9400e+02 5.1300e+02 4.7900e+02
 8.8200e+02 9.6500e+02 7.1000e+02 8.5300e+02 1.2080e+03 1.4100e+02
 3.3800e+02 4.0000e+02 3.5100e+02 6.1000e+02 7.0700e+02 5.5300e+02
 6.4900e+02 9.8700e+02 1.8600e+02 1.4500e+02 4.5600e+02 4.4300e+02
 4.1300e+02 5.2200e+02 4.9100e+02 9.1300e+02 9.9400e+02 7.2700e+02
 8.9400e+02 2.4800e+02 2.5300e+02 3.2000e+02 3.8200e+02 4.9900e+02
 1.2500e+03 1.0950e+03 1.5600e+03 1.4900e+03 1.9220e+03 2.2370e+03
 1.9040e+03 2.2530e+03 2.7310e+03 1.6400e+02 1.7150e+03 1.6780e+03
 1.5700e+03 2.0960e+03 1.9410e+03 3.0530e+03 3.3850e+03 2.5730e+03
 3.0620e+03 3.5730e+03 2.6000e+02 3.2600e+02 5.5500e+02 3.9100e+02
 5.0900e+02 9.7000e+01 1.3410e+03 1.1400e+03 1.6030e+03 1.5300e+03
 2.3020e+03 1.9600e+03 2.3110e+03 2.8020e+03 2.9100e+02 1.9600e+02
 7.1700e+02 5.1200e+02 1.7710e+03 1.7540e+03 1.6330e+03 2.1530e+03
 1.9890e+03 3.1830e+03 3.4870e+03 2.6430e+03 3.2130e+03 3.7240e+03
 2.4700e+02 4.2800e+02 4.5200e+02 3.7900e+02 3.2300e+02 4.2700e+02
 5.5900e+02 5.1600e+02 8.2900e+02 8.2700e+02 6.1600e+02 7.2400e+02
 9.9500e+02 3.1600e+02 4.3800e+02 5.6100e+02 5.9600e+02 4.7000e+02

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",         
    "SEX",                
    "COMP_REASWITHDRAWAL",     
    "OBS_STATUS",         
    "Stato_osservazione" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (4412, 5)
Colonne rimanenti: ['Territorio', 'Sesso', 'Denucia_motivo_ritiro', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Denucia_motivo_ritiro": "stato_denuncia",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})

# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: stato_denuncia
['Denuncia' 'Ritira la denuncia' 'Non denuncia' 'Non risponde'
 'Non disponibile' 'Tutte le voci']

Colonna: periodo
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.]

Colonna: numero_vittime
[3.7000e+01 3.8000e+01 3.4000e+01 3.0000e+01 1.9000e+01 4.3000e+01
 6.9000e+01 2.2000e+01 4.7000e+01 4.4000e+01 3.0000e+00 1.1000e+01
 4.0000e+00 9.0000e+00 7.0000e+00 1.0000e+00 2.1000e+02 2.1100e+02
 1.8300e+02 1.7900e+02 1.6000e+02 3.0300e+02 2.8800e+02 1.8200e+02
 3.1200e+02 3.3100e+02 2.0000e+00 5.0000e+00 5.5000e+01 3.6000e+01
 6.0000e+01 3.3000e+01 6.4000e+01 2.1200e+02 1.7100e+02 1.5000e+01
 3.1100e+02 2.9500e+02 2.8600e+02 2.6100e+02 2.1800e+02 5.7100e+02
 5.4000e+02 2.6200e+02 4.2500e+02 4.3300e+02 1.0980e+03 1.1770e+03
 1.1500e+03 1.3330e+03 1.2910e+03 1.6100e+03 2.1150e+03 1.5000e+03
 1.9700e+03 1.9920e+03 2.9300e+02 3.4100e+02 2.5600e+02 2.7900e+02
 3.7600e+02 3.1800e+02 2.8100e+02 4.6500e+02 5.7100e+03 5.7280e+03
 5.5350e+03 6.6970e+03 6.0810e+03 8.9580e+03 9.9070e+03 8.0560e+03
 1.0322e+04 1.2319e+04 3.9000e+01 4.5000e+01 3.5000e+01 2.7000e+01
 1.2100e+02 2.2100e+02 2.0600e+02 1.5350e+03 9.2600e+02 6.2200e+02
 5.4500e+02 8.1300e+02 9.9000e+02 7.4900e+02 4.1510e+03 3.1010e+03
 1.5520e+03 3.4700e+02 4.1500e+02 7.7700e+03 7.8300e+03 7.7990e+03
 9.3410e+03 8.4270e+03 1.5128e+04 1.5720e+04 1.1632e+04 1.4455e+04
 1.6117e+04 2.0000e+01 6.0000e+00 2.9000e+01 3.1000e+01 5.7000e+01
 2.3000e+01 1.2000e+01 1.2960e+03 1.0210e+03 1.4030e+03 1.0810e+03
 1.1350e+03 1.2150e+03 1.1840e+03 1.3630e+03 1.3100e+03 1.6530e+03
 2.1840e+03 1.5220e+03 2.0370e+03 2.0420e+03 2.9600e+02 3.5200e+02
 2.5900e+02 2.9000e+02 2.8200e+02 2.9700e+02 3.8300e+02 3.1900e+02
 4.7200e+02 5.9200e+03 5.9390e+03 5.7180e+03 6.8760e+03 6.2410e+03
 9.2610e+03 1.0195e+04 8.2380e+03 1.0663e+04 1.2681e+04 4.8000e+01
 4.1000e+01 1.2500e+02 2.2600e+02 2.0800e+02 1.6470e+03 9.8500e+02
 6.8300e+02 5.7800e+02 8.7700e+02 1.0370e+03 7.8500e+02 4.3720e+03
 3.2840e+03 1.6220e+03 1.6500e+03 1.4510e+03 8.0820e+03 8.1250e+03
 8.0850e+03 9.6020e+03 8.6470e+03 1.5708e+04 1.6272e+04 1.1909e+04
 1.6283e+04 1.7631e+04 8.0000e+00 1.0000e+01 5.9000e+01 5.0000e+01
 4.2000e+01 6.6000e+01 7.6000e+01 6.7000e+01 1.3000e+01 2.4000e+01
 7.2000e+01 7.1000e+01 6.1000e+01 5.6000e+01 1.0200e+02 1.0300e+02
 5.1000e+01 9.6000e+01 9.0000e+01 3.0000e+02 3.4600e+02 2.7800e+02
 3.2200e+02 4.1400e+02 4.9600e+02 3.5600e+02 4.4700e+02 5.1000e+02
 8.5000e+01 8.0000e+01 7.4000e+01 7.5000e+01 1.1700e+02 8.3000e+01
 1.2200e+02 1.5660e+03 1.6750e+03 1.5410e+03 1.7130e+03 1.6430e+03
 2.3170e+03 2.4020e+03 2.1570e+03 2.5390e+03 3.3870e+03 2.1000e+01
 4.6000e+01 2.4100e+02 1.3100e+02 9.4000e+01 1.6300e+02 1.8700e+02
 7.4500e+02 4.7100e+02 2.0770e+03 2.2130e+03 2.0750e+03 2.3200e+03
 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03 3.3840e+03 4.3350e+03
 7.0000e+01 3.0500e+02 3.5400e+02 2.8500e+02 3.4500e+02 3.2700e+02
 4.2400e+02 5.1100e+02 3.5800e+02 4.6200e+02 5.2000e+02 8.8000e+01
 6.5000e+01 7.7000e+01 1.1900e+02 8.4000e+01 1.2300e+02 1.6250e+03
 1.7230e+03 1.5910e+03 1.7600e+03 1.6850e+03 2.3830e+03 2.4610e+03
 2.1940e+03 2.6230e+03 3.4580e+03 1.4000e+01 1.6000e+01 2.5700e+02
 1.3800e+02 9.9000e+01 1.7600e+02 1.9500e+02 1.2400e+02 7.6900e+02
 4.9800e+02 1.7000e+02 9.3000e+01 2.1490e+03 2.2770e+03 2.1460e+03
 2.3810e+03 2.2150e+03 3.6740e+03 3.6350e+03 2.8450e+03 3.5500e+03
 4.4750e+03 1.8000e+01 2.8000e+01 2.6000e+01 8.2000e+01 1.0900e+02
 9.8000e+01 1.1800e+02 1.5400e+02 1.0000e+02 1.1200e+02 2.5000e+01
 1.7000e+01 4.9400e+02 4.6400e+02 5.2700e+02 4.7500e+02 6.3300e+02
 6.3100e+02 5.8300e+02 6.7100e+02 8.3900e+02 9.1000e+01 1.2000e+02
 6.4500e+02 6.8400e+02 6.2300e+02 7.0900e+02 6.3200e+02 9.5200e+02
 7.4700e+02 9.1100e+02 1.0760e+03 1.0600e+02 1.0100e+02 1.5900e+02
 3.2000e+01 5.1500e+02 5.3300e+02 4.8200e+02 5.3700e+02 4.8600e+02
 6.5200e+02 6.5000e+02 5.9200e+02 6.8600e+02 8.6100e+02 5.8000e+01
 2.1300e+02 1.3200e+02 6.6900e+02 7.0300e+02 6.5100e+02 7.2200e+02
 6.4700e+02 1.0110e+03 9.8800e+02 7.5900e+02 9.4800e+02 1.1120e+03
 1.5700e+02 1.4600e+02 1.5100e+02 2.1700e+02 2.0900e+02 1.8100e+02
 2.7700e+02 5.4000e+01 5.2000e+01 2.0500e+02 2.2800e+02 1.8400e+02
 3.0700e+02 3.1000e+02 2.3100e+02 2.6300e+02 3.6000e+02 1.6200e+02
 1.6600e+02 1.5500e+02 2.2300e+02 2.1400e+02 6.2000e+01 2.1500e+02
 1.8800e+02 2.3400e+02 1.8900e+02 2.3500e+02 3.7000e+02 4.0000e+01
 1.8000e+02 2.0100e+02 2.6700e+02 3.0200e+02 3.4800e+02 4.9000e+01
 7.8000e+01 9.0700e+02 9.2400e+02 1.0190e+03 1.4570e+03 1.5570e+03
 1.3830e+03 2.2540e+03 1.4700e+02 5.3000e+01 2.9900e+02 1.0800e+02
 1.3090e+03 1.2600e+03 1.3740e+03 1.3340e+03 2.2630e+03 2.2640e+03
 1.8020e+03 2.2040e+03 2.8770e+03 1.9200e+02 2.0300e+02 2.7300e+02
 3.1300e+02 3.5700e+02 7.9000e+01 9.3900e+02 1.0180e+03 9.5000e+02
 1.0490e+03 1.0380e+03 1.4980e+03 1.5920e+03 1.4070e+03 1.7100e+03
 2.2980e+03 1.2900e+02 4.8800e+02 1.1400e+02 1.2560e+03 1.3480e+03
 1.2970e+03 1.4150e+03 1.3700e+03 2.3240e+03 2.3220e+03 1.8350e+03
 2.3180e+03 2.9690e+03 1.2700e+02 1.5800e+02 2.5000e+02 3.6900e+02
 8.0300e+02 7.7800e+02 7.4800e+02 9.5800e+02 8.5900e+02 1.3070e+03
 1.5640e+03 1.2760e+03 2.3550e+03 1.5200e+02 6.3000e+01 1.0500e+02
 4.3400e+02 3.4000e+02 1.0260e+03 1.0090e+03 9.7500e+02 1.2550e+03
 1.1960e+03 2.0050e+03 2.2780e+03 1.7020e+03 2.1750e+03 3.0120e+03
 1.3700e+02 1.9100e+02 2.5100e+02 9.2000e+01 8.0600e+02 7.7200e+02
 9.7900e+02 8.8400e+02 1.3560e+03 1.6000e+03 1.3000e+03 1.6650e+03
 2.4060e+03 2.0400e+02 1.0700e+02 4.5700e+02 1.0750e+03 1.0480e+03
 1.2860e+03 1.2280e+03 2.0830e+03 2.3390e+03 1.7310e+03 2.2710e+03
 3.1140e+03 1.1000e+02 1.1500e+02 1.4000e+02 1.5000e+02 1.1300e+02
 6.8000e+01 1.1100e+02 1.3500e+02 3.6500e+02 4.4800e+02 4.3700e+02
 6.0600e+02 7.7100e+02 6.3400e+02 7.4300e+02 1.0630e+03 1.6700e+02
 4.8000e+02 4.6800e+02 6.1400e+02 6.1100e+02 9.5600e+02 1.1410e+03
 1.0140e+03 1.3930e+03 1.7700e+02 3.9500e+02 4.6300e+02 4.4900e+02
 6.2900e+02 7.8700e+02 6.4400e+02 7.6200e+02 1.0840e+03 7.3000e+01
 2.2400e+02 1.7300e+02 5.0400e+02 4.9000e+02 6.2600e+02 9.9200e+02
 1.1690e+03 8.7100e+02 1.0560e+03 1.4360e+03 8.7000e+01 8.1000e+01
 1.0400e+02 1.3600e+02 1.2800e+02 1.6100e+02 1.6900e+02 1.3000e+02
 1.6800e+02 8.9000e+01 1.1600e+02 1.7500e+02 2.6900e+02 1.3900e+02
 3.5000e+02 3.9700e+02 5.9000e+02 6.8900e+02 5.4100e+02 9.6300e+02
 1.7800e+02 4.2300e+02 3.9400e+02 5.1300e+02 4.7900e+02 8.8200e+02
 9.6500e+02 7.1000e+02 8.5300e+02 1.2080e+03 1.4100e+02 3.3800e+02
 4.0000e+02 3.5100e+02 6.1000e+02 7.0700e+02 5.5300e+02 6.4900e+02
 9.8700e+02 1.8600e+02 1.4500e+02 4.5600e+02 4.4300e+02 4.1300e+02
 5.2200e+02 4.9100e+02 9.1300e+02 9.9400e+02 7.2700e+02 8.9400e+02
 2.4800e+02 2.5300e+02 3.2000e+02 3.8200e+02 4.9900e+02 1.2500e+03
 1.0950e+03 1.5600e+03 1.4900e+03 1.9220e+03 2.2370e+03 1.9040e+03
 2.2530e+03 2.7310e+03 1.6400e+02 1.7150e+03 1.6780e+03 1.5700e+03
 2.0960e+03 1.9410e+03 3.0530e+03 3.3850e+03 2.5730e+03 3.0620e+03
 3.5730e+03 2.6000e+02 3.2600e+02 5.5500e+02 3.9100e+02 5.0900e+02
 9.7000e+01 1.3410e+03 1.1400e+03 1.6030e+03 1.5300e+03 2.3020e+03
 1.9600e+03 2.3110e+03 2.8020e+03 2.9100e+02 1.9600e+02 7.1700e+02
 5.1200e+02 1.7710e+03 1.7540e+03 1.6330e+03 2.1530e+03 1.9890e+03
 3.1830e+03 3.4870e+03 2.6430e+03 3.2130e+03 3.7240e+03 2.4700e+02
 4.2800e+02 4.5200e+02 3.7900e+02 3.2300e+02 4.2700e+02 5.5900e+02
 5.1600e+02 8.2900e+02 8.2700e+02 6.1600e+02 7.2400e+02 9.9500e+02
 3.1600e+02 4.3800e+02 5.6100e+02 5.9600e+02 4.7000e+02 7.9900e+02
 1.8500e+02 3.8900e+02 3.4400e+02 4.5000e+02 5.7300e+02 5.1900e+02
 8.6900e+02 8.5800e+02 6.3800e+02 1.0340e+03 1.4200e+02 1.4900e+02
 1.6500e+02 1.4400e+02 1.7200e+02 2.0000e+02 2.2000e+02 1.5600e+02
 1.2600e+02 2.3700e+02 1.9800e+02 2.7400e+02 3.4300e+02 3.6100e+02
 2.4400e+02 1.9000e+02 2.8300e+02 2.3000e+02 3.0100e+02 3.5300e+02
 2.6400e+02 3.7800e+02 3.5500e+02 2.9200e+02 7.5600e+02 7.8000e+02
 6.0100e+02 1.1230e+03 1.3130e+03 1.1560e+03 1.5160e+03 4.1900e+02
 1.0580e+03 8.7200e+02 1.1950e+03 1.1450e+03 1.7970e+03 2.0440e+03
 1.8750e+03 3.6400e+02 2.2500e+02 3.0400e+02 2.9800e+02 7.8600e+02
 8.1100e+02 8.8700e+02 8.9100e+02 1.1680e+03 1.3450e+03 1.1830e+03
 1.3920e+03 1.5550e+03 4.3900e+02 3.2800e+02 1.0450e+03 1.1010e+03
 9.0500e+02 1.2320e+03 1.1820e+03 1.8690e+03 2.1040e+03 1.5870e+03
 1.9750e+03 2.0920e+03 2.7600e+02 3.9600e+02 8.6000e+01 1.3120e+03
 1.1110e+03 1.4670e+03 1.2750e+03 1.8160e+03 2.0090e+03 1.6260e+03
 1.6570e+03 2.1560e+03 6.0400e+02 4.0200e+02 1.8100e+03 1.8060e+03
 2.8820e+03 3.0050e+03 2.1960e+03 2.3770e+03 2.8370e+03 3.7400e+02
 4.7800e+02 3.3300e+02 3.9800e+02 4.1000e+02 1.3580e+03 1.2640e+03
 1.1440e+03 1.5080e+03 1.8590e+03 2.0610e+03 1.6490e+03 1.7030e+03
 2.2210e+03 2.4200e+02 1.3300e+02 6.3000e+02 4.2100e+02 1.4800e+02
 1.8830e+03 1.7760e+03 1.5930e+03 2.0990e+03 1.8490e+03 2.9640e+03
 3.0890e+03 2.2340e+03 2.4810e+03 1.9900e+02 1.9300e+02 1.7400e+02
 2.8900e+02 2.7200e+02 2.5800e+02 2.3900e+02 2.7500e+02 6.2800e+02
 6.8000e+02 5.9100e+02 8.9200e+02 6.9400e+02 9.7200e+02 8.7400e+02
 8.3000e+02 9.6000e+02 8.4500e+02 1.2950e+03 1.3720e+03 9.6800e+02
 1.0330e+03 1.2870e+03 1.4300e+02 2.2900e+02 5.2400e+02 6.9800e+02
 6.0900e+02 8.2600e+02 9.1400e+02 7.0500e+02 7.2100e+02 1.0040e+03
 9.0400e+02 8.6200e+02 8.6400e+02 1.3230e+03 9.9100e+02 1.0830e+03
 9.5000e+01 3.3000e+02 4.1800e+02 3.3600e+02 6.2700e+02 4.8300e+02
 5.0200e+02 4.9500e+02 8.2000e+02 8.7900e+02 6.3500e+02 6.7800e+02
 8.8900e+02 3.6800e+02 3.3900e+02 4.8900e+02 7.0800e+02 8.5200e+02
 9.0200e+02 6.4200e+02 7.0600e+02 9.2900e+02 3.2400e+02 2.4500e+02
 2.6600e+02 1.9700e+02 1.9400e+02 3.5900e+02 5.6300e+02 5.0600e+02
 5.5000e+02 4.9200e+02 7.2800e+02 7.6300e+02 8.3800e+02 7.7700e+02
 7.8400e+02 7.0000e+02 1.1170e+03 1.1970e+03 1.0880e+03 5.5200e+02
 5.8200e+02 5.6600e+02 5.0500e+02 7.5300e+02 6.3600e+02 6.4000e+02
 8.0200e+02 7.4000e+02 8.0700e+02 7.1600e+02 1.1590e+03 9.2000e+02
 1.1300e+03 3.9200e+02 5.2100e+02 5.5100e+02 4.3200e+02 6.0500e+02
 5.4900e+02 8.6300e+02 4.0500e+02 4.0400e+02 3.6700e+02 5.3900e+02
 4.4000e+02 5.7000e+02 5.6500e+02 5.2500e+02 8.1500e+02 8.8800e+02
 6.8200e+02 8.1900e+02 2.0700e+02 2.3300e+02 2.2200e+02 3.3400e+02
 2.1900e+02 2.3600e+02 2.3200e+02 2.6500e+02 2.3800e+02 2.5400e+02
 7.9400e+02 8.2300e+02 1.6290e+03 1.4310e+03 1.1810e+03 9.2100e+02
 3.7300e+02 3.8800e+02 5.4400e+02 2.3950e+03 2.1720e+03 1.4050e+03
 2.5750e+03 1.2720e+03 1.1250e+03 8.3200e+02 8.4600e+02 8.2400e+02
 8.7300e+02 1.7210e+03 9.3600e+02 1.5320e+03 1.2730e+03 9.5900e+02
 1.3300e+03 9.3000e+02 5.6900e+02 2.5310e+03 2.3260e+03 1.4750e+03
 3.8480e+03 2.2190e+03]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige",
    "provincia autonoma bolzano / bozen": "bolzano",
    "provincia autonoma trento": "trento"
})


# Uniformazione minuscolo per la colonna sesso e stato_denuncia
df["sesso"] = df["sesso"].str.lower().str.strip()
df["stato_denuncia"] = df["stato_denuncia"].str.lower().str.strip()


# Rimozione delle voci aggregate "totale" e "tutte le voci"
# da sesso e stato_denuncia per evitare doppio conteggio

df = df[
    (df["sesso"] != "totale") &
    (df["stato_denuncia"] != "tutte le voci")
]


# Conversione delle colonne numeriche da float a integer

df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)


# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

  territorio   sesso stato_denuncia  periodo  numero_vittime
0     italia  maschi       denuncia     2015              37
1     italia  maschi       denuncia     2016              38
2     italia  maschi       denuncia     2017              34
3     italia  maschi       denuncia     2018              30
4     italia  maschi       denuncia     2019              19
5     italia  maschi       denuncia     2020              43
6     italia  maschi       denuncia     2021              69
7     italia  maschi       denuncia     2022              22
8     italia  maschi       denuncia     2023              47
9     italia  maschi       denuncia     2024              44

<class 'pandas.core.frame.DataFrame'>
Index: 2191 entries, 0 to 4345
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   territorio      2191 non-null   object
 1   sesso           2191 non-null   object
 2   stato_denuncia  2191 non-null   object
 3   periodo         2191 non-null   int64
 4   numero_vittime  2191 non-null   int64
dtypes: int64(2), object(3)
memory usage: 102.7+ KB

Missing values per colonna:

territorio        0
sesso             0
stato_denuncia    0
periodo           0
numero_vittime    0
dtype: int64

Numero valori unici per colonna:

numero_vittime    434
territorio         28
periodo            10
stato_denuncia      5
sesso               3
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' 'liguria' 'lombardia' 'nord est'
 'trentino alto adige' 'bolzano' 'trento' 'veneto' 'friuli venezia giulia'
 'emilia romagna' 'centro' 'toscana' 'umbria' 'marche' 'lazio' 'sud'
 'abruzzo' 'molise' 'campania' 'puglia' 'basilicata' 'calabria' 'isole'
 'sicilia' 'sardegna' 'non indicato']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: stato_denuncia
['denuncia' 'ritira la denuncia' 'non denuncia' 'non risponde'
 'non disponibile']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[   37    38    34    30    19    43    69    22    47    44     3    11
     4     9     7     1   210   211   183   179   160   303   288   182
   312   331     2     5    55    36    60    33    64   212   171    15
  1098  1177  1150  1333  1291  1610  2115  1500  1970  1992   293   341
   256   286   279   376   318   281   465  5710  5728  5535  6697  6081
  8958  9907  8056 10322 12319    39    45    35    27   121   221   206
  1535   926   622   545   813   990   749  4151  3101  1552   347   415
    20     6    29    31    57    23    12  1296  1021     8    10    59
    48    50    42    66    76    67    13    24   300   346   278   322
   414   496   356   447   510    71    85    80    74    75   117    83
   122  1566  1675  1541  1713  1643  2317  2402  2157  2539  3387    21
    46   295   241   131    94   163   187   745   471    18    14    84
   102    82   109    98   118   154   100   112    25    17    16   494
   520   464   527   475   633   631   583   671   839    91    28    51
   120    32   157   146   151   217   209   181   277    54    52    26
    41    40   180   176   188   201   267   302   226   305   348    49
    78    56   907   988   924  1019  1011  1457  1557  1383  1650  2254
   147    53   124   299   108   127   132   158   250   296   369   803
   778   748   958   859  1307  1564  1276  1622  2355   152    63    96
   105   434   340   110   115    79    62    68    99   111   135   191
   358   365   448   437   606   771   634   743  1063    92    72   213
   167    77    87   113    81   104   136   214   139   350   397   590
   689   541   963    58   178   137    65   248   273   253   320   352
   382   499    93  1297  1250  1095  1560  1490  1922  2237  1904  2253
  2731   269   186   164   684   490   168    90   116    88   247   428
   533   571   452   106   156   126   150   173   237   184   198   274
   177   204   355   220   292   756   780   601   861  1123  1313  1156
  1356  1516   101   419   310   276   468   327   394   396    86    70
  1312  1215  1111  1467  1275  1816  2009  1626  1657  2156   230   125
   123   128   129   604   402   140   169   199   193   196   133   114
   159   223   185   189   628   559   680   591   811   892   694   703
   972    73   282    95   330   418   336   522   627   483   502   175
   142   141   148   205   203   144   194   537   563   506   550   492
   728   763   626   838   235   195    89   378   344   392   359   521
   551   432   456   605   162   207   166   233   103   229   208   512
   254   794   823   383  1629   852   479   172   244  1431  1181   921
  1125   832]

In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/vittime.stato_denuncia.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/vittime.stato_denuncia.csv