In [1]:
import pandas as pd

df = pd.read_csv(
    "../raw/Popolazione per regione.csv",
    sep=";"
)

df.head()

,Regione,Età,Celibi,Coniugati,Divorziati,Vedovi,Uniti civilmente,Maschi già in unione civile (per scioglimento unione),Maschi già in unione civile (per decesso del partner),Totale maschi,Nubili,Coniugate,Divorziate,Vedove,Unite civilmente,Femmine già in unione civile (per scioglimento unione),Femmine già in unione civile (per decesso del partner),Totale femmine,Totale
0,Abruzzo,0,3821,0,0,0,0,0,0,3821,3553,0,0,0,0,0,0,3553,7374
1,Abruzzo,1,3992,0,0,0,0,0,0,3992,3658,0,0,0,0,0,0,3658,7650
2,Abruzzo,2,4239,0,0,0,0,0,0,4239,3919,0,0,0,0,0,0,3919,8158
3,Abruzzo,3,4296,0,0,0,0,0,0,4296,4165,0,0,0,0,0,0,4165,8461
4,Abruzzo,4,4453,0,0,0,0,0,0,4453,4186,0,0,0,0,0,0,4186,8639

In [2]:
# Standardizzazione automatica nomi colonne:
# - tutto minuscolo

df.columns = df.columns.str.lower()

# Rinomina colonne in modo standardizzato (snake_case, senza accenti/spazi)
df = df.rename(columns={
    "regione": "territorio",
    "uniti civilmente": "uniti_civilmente",
    "maschi già in unione civile (per scioglimento unione)": "maschi_ex_unione_scioglimento",
    "maschi già in unione civile (per decesso del partner)": "maschi_ex_unione_decesso",
    "totale maschi": "totale_maschi",
    "coniugate": "coniugate",
    "unite civilmente": "unite_civilmente",
    "femmine già in unione civile (per scioglimento unione)": "femmine_ex_unione_scioglimento",
    "femmine già in unione civile (per decesso del partner)": "femmine_ex_unione_decesso",
    "totale femmine": "totale_femmine"
})

# Visualizza nomi colonne
df.columns.tolist()

['territorio',
 'età',
 'celibi',
 'coniugati',
 'divorziati',
 'vedovi',
 'uniti_civilmente',
 'maschi_ex_unione_scioglimento',
 'maschi_ex_unione_decesso',
 'totale_maschi',
 'nubili',
 'coniugate',
 'divorziate',
 'vedove',
 'unite_civilmente',
 'femmine_ex_unione_scioglimento',
 'femmine_ex_unione_decesso',
 'totale_femmine',
 'totale']

In [3]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: territorio
Numero valori unici: 20
Valori unici:
['Abruzzo' 'Basilicata' 'Calabria' 'Campania' 'Emilia-Romagna'
 'Friuli-Venezia Giulia' 'Lazio' 'Liguria' 'Lombardia' 'Marche' 'Molise'
 'Piemonte' 'Puglia' 'Sardegna' 'Sicilia' 'Toscana'
 'Trentino-Alto Adige/Südtirol' 'Umbria' "Valle d'Aosta/Vallée d'Aoste"
 'Veneto']


============================================================
Colonna: età
Numero valori unici: 102
Valori unici:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 999]


============================================================
Colonna: celibi
Numero valori unici: 1731
Valori unici:
[   3821    3992    4239 ...     128     112 1164711]


============================================================
Colonna: coniugati
Numero valori unici: 1452
Valori unici:
[      0       1       2 ...     343     205 1078774]


============================================================
Colonna: divorziati
Numero valori unici: 803
Valori unici:
[     0      1      2      4      9     10     12     19     30     31
     58     81     82     92    118    164    189    225    239    256
    316    364    389    458    485    532    580    631    682    624
    692    691    733    728    768    719    666    667    641    584
    497    468    437    475    397    342    332    283    250    240
    216    190    193    155    107    101     71     53     62     76
     41     34     27     23      6      7      5  18774     11     14
     17     25     37     32     46     47     80     84    109    114
    128    163    169    177    194    182    195    172    171    183
    187    203    175    137    131    126    129    127    102     93
     73     74     59     36     21     13     15      3   5185      8
     18     28     39     57     88    105    115    186    241    242
    302    303    353    370    423    450    448    558    542    547
    559    605    583    628    591    608    620    541    490    531
    538    503    444    464    359    371    327    329    267    210
    247    133    111     79     69     54  17093     16     33     48
     87     94    159    199    232    311    341    442    488    597
    600    717    741    888    893   1078   1132   1291   1384   1426
   1478   1578   1596   1586   1598   1617   1667   1691   1649   1539
   1442   1319   1273   1161   1026   1045    928    858    766    689
    598    564    554    466    443    404    363    248    201    150
    110     38  44646     29     44     42     72     49     75    121
    207    222    309    536    803    937   1047   1222   1375   1520
   1778   2101   2241   2409   2597   2835   2983   3035   3084   3318
   3327   3336   3359   3184   3043   2873   2727   2652   2340   2242
   2149   1923   1701   1509   1355   1283   1284   1195   1095   1029
    905    578    414    416    337    284    244    174     89     64
     24  86131     61     97    141    138    144    173    257    324
    457    473    567    676    701    760    870    953    939    994
   1005   1032   1082    983    971    875    860    837    672    602
    550    529    456    403    394    421    358    291    272    200
  26198     56    166    226    288    333    399    494    706    872
    922   1063   1324   1493   1645   1902   2135   2414   2695   2762
   2979   2996   3340   3334   3509   3756   3751   3780   3532   3470
   3159   2858   2731   2531   2382   2223   2006   1928   1648   1537
   1432   1339   1269   1149   1081    914    679    638    574    509
    426    401    318    213    135  92141     20     66    149    220
    277    307    362    387    454    568    722    885   1055   1085
   1158   1243   1299   1351   1437   1577   1326   1245   1206   1186
   1064   1035    940    871    814    671    668    617    581    514
    534    478    420    278    295    230    212    142    108     67
     50  36615     55     78     68    161    202    258    321    441
    566    659    853    981   1251   1434   1628   1917   2257   2412
   2743   3258   3573   4232   4668   5454   5608   5961   6362   6485
   7071   6934   7168   7365   7522   7337   6584   6175   5830   5186
   4867   4384   4122   3784   3406   3093   2758   2562   2317   2109
   1871   1869   1502   1038    930    779    726    587    476    304
    208    134     60     22 178298     43    154    176    249    328
    400    491    537    619    579    680    794    835    874    958
    942   1000    975   1046    889    781    685    614    504    419
    395    347    335    287    238    181    119    123     98     65
  24671     35     85    100     86    113    117    122    143    125
     63     52     40   3371    112    280    382    524    555    616
    790    833   1023   1121   1253   1453   1640   2233   2458   2680
   2837   3023   3062   3272   3452   3593   3658   3716   3325   3160
   3105   2931   2706   2457   2400   2179   1983   1879   1674   1569
   1323   1300   1207   1131   1061    952    626    575    447    435
    402    260    209    130  91658     91    147    234    343    427
    432    527    612    769    859    961   1097   1203   1308   1473
   1620   1590   1634   1753   1641   1666   1585   1599   1440   1348
   1199   1282   1204   1006   1059    834    817    737    663    522
    276    191    157    104  43490    153    243    296    330    405
    460    519    819    844    862    966    962   1014   1051    997
   1074   1024    984    865    836    734    696    654    606    573
    393    265  26311    162    273    440    525    629    792    901
   1050   1127   1275   1423   1536   1690   1685   1818   1886   1896
   1998   1982   1985   2016   1988   2000   1789   1809   1650   1297
   1298   1145    996    906    749    683    560    526    282    168
    120  54531    245    275    455    496    549    738    927   1058
   1278   1525   1723   1846   2052   2171   2271   2404   2650   2605
   2818   2906   2887   2679   2577   2375   2281   1908   1626   1523
   1400   1230   1071   1021    980    912    820    351    294    197
     90     83     26  70285    198    206    336    365    585    656
    774    725    828    816    752    603    523    434    385    344
    279    217    152     96     51  19066     70    253    274    361
    390    463    507    501    557    517    483    339    215  13978
    124     95     45    167    218    352    412    688    818    955
   1175   1305   1498   1632   2266   2488   2848   3039   3130   3524
   3392   3480   3594   3735   3740   3416   3166   2963   2563   2535
   2237   2005   1901   1656   1304   1214   1114   1048    929    745
    297    140  86398]


============================================================
Colonna: vedovi
Numero valori unici: 767
Valori unici:
[     0      1      4      2      7      9     11     15     14     16
     12     26     18     32     22     34     33     58     45     62
     63     52     67     71     98    100    126    155    168    162
    183    190    197    225    246    268    274    329    350    320
    385    391    440    485    491    551    565    408    505    523
    569    608    673    670    683    661    574    559    495    421
    361    316    280    177    141    103  16330      6      3     13
     17     23     30     36     39     56     66     84     92     72
     87     91     97    101    131    149    143    157    169    165
    201    214    217    240    226    182    224    207    229    289
    297    302    285    278    231    244    212    203    127     70
     54     38     24   7208      5     20     35     43     53     88
    109    123    175    192    223    276    267    292    318    347
    353    424    381    486    544    517    583    627    711    714
    773    779    651    698    689    752    725    946    930    860
    866    836    812    685    702    538    417    369    245    210
    159    107     69  23166     48     47    106     85    133    151
    164    195    265    272    322    365    409    438    514    568
    713    887    919    957   1056   1109   1248   1271   1426   1514
   1619   1697   1705   1759   1947   2100   2213   2583   2617   2811
   2517   2214   2338   2405   2417   2711   2702   2473   2228   2094
   1907   1621   1445   1211    960    802    552    375    215    181
    116    184  70979     19     25     31     41     28     68    135
    186    200    222    239    252    295    411    423    468    516
    572    684    721    787    858    842    986   1031   1128   1157
   1282   1389   1496   1662   1951   2112   2281   1765   2056   2218
   2202   2399   2603   2772   2713   2523   2181   2198   2031   1387
   1202    977    703    498    397    242    145    253  61053     10
     50     46     61     76    102    110    152    185    178    237
    282    314    331    386    476    550    613    503    679    666
    677    808    863    762    727    600    571    462    414    346
    170    124     37  17201     40     57     86    105    119    132
    220    196    241    273    312    349    466    494    598    615
    730    810    769    896   1012   1077   1094   1269   1321   1480
   1503   1593   1617   1852   2105   2369   2608   2556   2168   2355
   2479   2581   2767   3156   3085   2822   2748   2432   2352   2095
   1659   1421   1259   1048    738    388    251    281  71602      8
     44     64     83     95    146    179    194    233    257    337
    396    457    460    504    620    774    843    750    856    874
   1061   1095   1137   1081    935    828    756    630    563    213
    137     77  23733     65     93    249    378    459    500    541
    573    628    726    783   1060   1070   1177   1214   1356   1488
   1626   1673   1827   1864   2196   2205   2478   2612   2779   2997
   3477   3795   4173   4348   4896   3871   4306   4528   4713   5066
   5793   5775   5719   4935   4321   4196   3606   2943   2628   2069
   1674   1154    581    248    305 127120     29     27     75     79
     90    108    118    154    176    199    232    341    392    433
    536    527    619    623    645    605    693    667    663    782
    862    879    678    710    657    548    410    293    238     82
  19649     42    129    128    147    113    120    160    171    115
   4053     21    114    142    259    291    371    464    512    621
    712    805    865    893   1021   1209   1291   1414   1473   1678
   1851   2129   2229   2411   1883   2232   2446   2457   2879   2915
   2828   2594   2342   2199   1905   1563   1333    650    425    299
  62895    125    173    343    333    465    567    596    747    770
    852    851    948   1017   1120   1115   1317   1350   1464   1740
   1811   1891   1722   1629   1731   1941   2133   2207   2071   1884
   1841   1721   1554   1351   1122    952    811    549    416    112
  51989    150    187    261    301    317    338    334    399    437
    482    471    518    526    634    618    687    695    723    682
    642    790    699    855    829    715    643    594    509    422
    368    279    243    161     73     81  20513     59    138    191
    230    483    490    641    674    724    823    956    966   1036
   1251   1349   1320   1405   1505   1842   2029   2096   2119   1914
   1877   2042   2025   2381   2348   2190   1969   1857   1835   1730
   1459   1156   1002    799    202    204  59004     78    188    256
    351    469    547    599    668    717    870    901    971   1042
   1091   1219   1309   1727   1858   2106   1752   1898   1879   2013
   2385   2395   2437   1983   1585   1437   1140   1011    791    625
    439    328    209  52908     49     74     96    227    254    362
    364    434    339    455    444    481    496    412    313    275
    269    104  11456    136    172    260    310    359    370    330
    477    493    535    553    484    389  11890     55     80   1671
    294    315    325    390    543    766    824    830    958   1101
   1217   1376   1489   1590   1753   1970   2098   2371   1793   2124
   2366   2396   2476   2716   2655   2540   2351   2012   1977   1770
   1413   1231    987    798    562    153  60789]


============================================================
Colonna: uniti_civilmente
Numero valori unici: 146
Valori unici:
[   0    1    3    2    4    8    9    6   11   10    7   12    5  282
   35  145   14   18   19   17   23   27   28   26   20   24   31   25
   32   29   13   15 1015   16   33   47   45   46   51   60   40   63
   56   59   58   73   52   66   68   81   78   88   87   71   76   84
   67   57   44   39   36 2503   22  453   61   62   97   98   74   92
   86  115   94  111  105   95  118  117  122  114  116  129  128  124
  120   80   83   70   77   42   34 3989   21   30  763   55   89  141
  189  169  180  137  171  168  201  163  204  214  239  199  195  196
  191  185  203  194  184  156  147  148  134  108   91   69   38   43
 6818  439   53   72   50   90   64   37 2422  767  466 1074   41   49
   48 1636  437  341   65 2206]


============================================================
Colonna: maschi_ex_unione_scioglimento
Numero valori unici: 25
Valori unici:
[  0   1   5   2   9   4   3  32   6  71  12   8   7  98  25  10  11  13
 221  97  18  37  62  20  70]


============================================================
Colonna: maschi_ex_unione_decesso
Numero valori unici: 18
Valori unici:
[  0   1   3   2  11  48  12   4  47   5   8   6   7 165  58  16  31  41]


============================================================
Colonna: totale_maschi
Numero valori unici: 1957
Valori unici:
[   3821    3992    4239 ...     181     231 2392989]


============================================================
Colonna: nubili
Numero valori unici: 1763
Valori unici:
[  3553   3658   3919 ...     92    180 973508]


============================================================
Colonna: coniugate
Numero valori unici: 1455
Valori unici:
[      0       1       5 ...     108      70 1086346]


============================================================
Colonna: divorziate
Numero valori unici: 933
Valori unici:
[     0      1      3      4      5     12     19     37     36     47
     78     96    124    137    173    221    261    287    306    374
    393    476    526    587    598    630    777    810    813    859
    861    892    926    911    902    850    907    798    702    679
    672    590    551    497    434    462    400    373    345    324
    276    248    217    185    145    141    110    101     94     64
     63     38     33     20     21     15     18      8      2  24859
     14     24     39     61     65     54     82     90    123    112
    130    150    158    208    229    216    204    254    252    233
    223    218    231    239    210    193    165    192    174    134
    128    114     92    105     74     84     69     67     73     49
     41     26     27     17     11     10     16      7      6   6529
     28     57     60     81     93    136    195    269    301    329
    370    437    442    473    536    576    639    686    701    682
    712    763    815    738    776    752    683    697    649    583
    539    574    491    496    457    436    395    355    305    281
    241    222    194    170    116    104     97     80     91     75
     31     34     23     13  22922     55    142    279    367    447
    571    593    694    789    917   1003   1112   1222   1330   1517
   1632   1697   1855   1985   2125   2143   2230   2292   2296   2270
   2418   2262   2269   2041   1865   1826   1649   1583   1488   1477
   1306   1242   1196    965    946    865    845    761    730    618
    563    430    343    298    247    230    198    154    161    125
     89     83     48      9  68418     40     52    138    171    270
    339    439    502    725    885   1012   1187   1321   1436   1513
   1779   1967   2172   2497   2749   3118   3329   3513   3755   3898
   4098   4213   4294   4190   4309   4252   4346   4018   3841   3605
   3636   3182   3048   2835   2679   2510   2297   2137   1764   1765
   1586   1403   1327    879    842    769    680    636    600    332
    169    139     58     25 121467     43     95    133    181    266
    322    404    427    500    506    668    792    886   1026   1074
   1059   1119   1234   1166   1229   1326   1353   1282   1338   1198
   1137   1117   1013   1015    896    873    805    760    719    602
    542    501    517    455    413    296    275    211    209    178
    157     77     29  36273     45     72    120    159    213    264
    334    443    603    976   1151   1304   1472   1701   1866   2278
   2452   2854   2991   3482   3799   3959   4228   4530   4770   4918
   4955   5202   5144   5168   5250   4897   4539   4199   4096   3848
   3641   3311   3179   2882   2799   2373   2390   2228   2181   1981
   1894   1756   1705   1254   1141   1121    981    891    622    456
    426    318     76     44     32 142000     35     88    111    147
    219    245    336    366    382    529    566    669    817    920
    980   1276   1333   1556   1577   1692   1757   1749   1827   1878
   1927   1944   1823   1708   1614   1500   1446   1346   1277   1228
   1099   1010    775    767    747    699    742    661    421    435
    347    319    323    283    160    152     22  51708     85    131
    162    240    335    523    693    912   1096   1597   1966   2327
   2569   2959   3243   3688   4093   4457   5187   5773   6177   7085
   7504   7940   8167   8348   8728   8999   8998   9059   9061   9007
   8717   8208   7449   6835   6521   6023   5424   5117   4759   4423
   4032   3702   3387   3159   2954   2879   2844   2575   2548   1641
   1587   1452   1396   1263   1180    937    874    634    346    246
    220    143 247954    121    187    190    250    303    316    398
    471    498    581    670    772    806    834    948   1045   1028
   1107   1182   1169   1214   1208   1204   1152   1202   1140   1091
   1016   1031    836    784    624    468    396    410    356    299
    289    226    183    135     42  33049     98    151    144    119
    140    166    148    109    107     79     30   4105    214    327
    467    512    573    732    903   1093   1297   1519   1679   1877
   2029   2328   2604   3028   3362   3639   3721   4136   4281   4510
   4589   4690   4640   4610   4631   4168   3952   3812   3565   3322
   3085   2874   2744   2504   2326   2083   1953   1800   1726   1578
   1593   1339    897    797    635    612    570    485    375    267
     99     51 127384     50    186    224    321    405    580    684
    883    978   1129   1224   1410   1575   1639   1776   1930   1978
   2023   1999   1988   1977   2082   1982   2002   1974   1848   1576
   1432   1322   1232   1168   1051   1007    864    868    716    688
    524    392    314    199    113    103  59451    342    377    460
    503    577    646    729    774    882    968    991   1097   1127
   1206   1160   1179   1210   1148   1150   1142   1004   1006    913
    843    827    710    652    535    585    533    458    414    340
    290    274    127    100     59     46  32506    117    191    308
    397    511    707    858    993   1065   1200   1310   1535   1626
   1792   1854   2068   2203   2337   2413   2473   2540   2559   2669
   2598   2511   2492   2427   2434   2151   2101   1962   1798   1561

In [4]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose


df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "valle d'aosta/vallée d'aoste": "valle d'aosta",
    "trentino alto adige/südtirol": "trentino alto adige"
    })

# Verifica tipo delle colonne
df.dtypes

territorio                        object
età                                int64
celibi                             int64
coniugati                          int64
divorziati                         int64
vedovi                             int64
uniti_civilmente                   int64
maschi_ex_unione_scioglimento      int64
maschi_ex_unione_decesso           int64
totale_maschi                      int64
nubili                             int64
coniugate                          int64
divorziate                         int64
vedove                             int64
unite_civilmente                   int64
femmine_ex_unione_scioglimento     int64
femmine_ex_unione_decesso          int64
totale_femmine                     int64
totale                             int64
dtype: object

In [5]:
# Verifica finale post-pulizia (struttura + qualità base)
display(df.head(10))
df.info()

print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

print("\nRighe duplicate:", df.duplicated().sum())

for col in df.columns:
    print("\nColonna:", col)
    if col == "periodo":
        print(sorted(df[col].unique().tolist()))
    else:
        print(df[col].unique())

,territorio,età,celibi,coniugati,divorziati,vedovi,uniti_civilmente,maschi_ex_unione_scioglimento,maschi_ex_unione_decesso,totale_maschi,nubili,coniugate,divorziate,vedove,unite_civilmente,femmine_ex_unione_scioglimento,femmine_ex_unione_decesso,totale_femmine,totale
0,abruzzo,0,3821,0,0,0,0,0,0,3821,3553,0,0,0,0,0,0,3553,7374
1,abruzzo,1,3992,0,0,0,0,0,0,3992,3658,0,0,0,0,0,0,3658,7650
2,abruzzo,2,4239,0,0,0,0,0,0,4239,3919,0,0,0,0,0,0,3919,8158
3,abruzzo,3,4296,0,0,0,0,0,0,4296,4165,0,0,0,0,0,0,4165,8461
4,abruzzo,4,4453,0,0,0,0,0,0,4453,4186,0,0,0,0,0,0,4186,8639
5,abruzzo,5,4522,0,0,0,0,0,0,4522,4315,0,0,0,0,0,0,4315,8837
6,abruzzo,6,4698,0,0,0,0,0,0,4698,4502,0,0,0,0,0,0,4502,9200
7,abruzzo,7,5054,0,0,0,0,0,0,5054,4739,0,0,0,0,0,0,4739,9793
8,abruzzo,8,5287,0,0,0,0,0,0,5287,4972,0,0,0,0,0,0,4972,10259
9,abruzzo,9,5406,0,0,0,0,0,0,5406,5042,0,0,0,0,0,0,5042,10448

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   territorio                      2040 non-null   object
 1   età                             2040 non-null   int64
 2   celibi                          2040 non-null   int64
 3   coniugati                       2040 non-null   int64
 4   divorziati                      2040 non-null   int64
 5   vedovi                          2040 non-null   int64
 6   uniti_civilmente                2040 non-null   int64
 7   maschi_ex_unione_scioglimento   2040 non-null   int64
 8   maschi_ex_unione_decesso        2040 non-null   int64
 9   totale_maschi                   2040 non-null   int64
 10  nubili                          2040 non-null   int64
 11  coniugate                       2040 non-null   int64
 12  divorziate                      2040 non-null   int64
 13  vedove                          2040 non-null   int64
 14  unite_civilmente                2040 non-null   int64
 15  femmine_ex_unione_scioglimento  2040 non-null   int64
 16  femmine_ex_unione_decesso       2040 non-null   int64
 17  totale_femmine                  2040 non-null   int64
 18  totale                          2040 non-null   int64
dtypes: int64(18), object(1)
memory usage: 302.9+ KB

Missing values per colonna:

territorio                        0
età                               0
celibi                            0
coniugati                         0
divorziati                        0
vedovi                            0
uniti_civilmente                  0
maschi_ex_unione_scioglimento     0
maschi_ex_unione_decesso          0
totale_maschi                     0
nubili                            0
coniugate                         0
divorziate                        0
vedove                            0
unite_civilmente                  0
femmine_ex_unione_scioglimento    0
femmine_ex_unione_decesso         0
totale_femmine                    0
totale                            0
dtype: int64

Numero valori unici per colonna:

totale                            1991
totale_femmine                    1969
totale_maschi                     1957
nubili                            1763
celibi                            1731
coniugate                         1455
coniugati                         1452
vedove                            1097
divorziate                         933
divorziati                         803
vedovi                             767
uniti_civilmente                   146
unite_civilmente                   109
età                                102
femmine_ex_unione_scioglimento      26
maschi_ex_unione_scioglimento       25
territorio                          20
maschi_ex_unione_decesso            18
femmine_ex_unione_decesso           13
dtype: int64

Righe duplicate: 0

Colonna: territorio
['abruzzo' 'basilicata' 'calabria' 'campania' 'emilia romagna'
 'friuli venezia giulia' 'lazio' 'liguria' 'lombardia' 'marche' 'molise'
 'piemonte' 'puglia' 'sardegna' 'sicilia' 'toscana' 'trentino alto adige'
 'umbria' "valle d'aosta" 'veneto']

Colonna: età
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 999]

Colonna: celibi
[   3821    3992    4239 ...     128     112 1164711]

Colonna: coniugati
[      0       1       2 ...     343     205 1078774]

Colonna: divorziati
[     0      1      2      4      9     10     12     19     30     31
     58     81     82     92    118    164    189    225    239    256
    316    364    389    458    485    532    580    631    682    624
    692    691    733    728    768    719    666    667    641    584
    497    468    437    475    397    342    332    283    250    240
    216    190    193    155    107    101     71     53     62     76
     41     34     27     23      6      7      5  18774     11     14
     17     25     37     32     46     47     80     84    109    114
    128    163    169    177    194    182    195    172    171    183
    187    203    175    137    131    126    129    127    102     93
     73     74     59     36     21     13     15      3   5185      8
     18     28     39     57     88    105    115    186    241    242
    302    303    353    370    423    450    448    558    542    547
    559    605    583    628    591    608    620    541    490    531
    538    503    444    464    359    371    327    329    267    210
    247    133    111     79     69     54  17093     16     33     48
     87     94    159    199    232    311    341    442    488    597
    600    717    741    888    893   1078   1132   1291   1384   1426
   1478   1578   1596   1586   1598   1617   1667   1691   1649   1539
   1442   1319   1273   1161   1026   1045    928    858    766    689
    598    564    554    466    443    404    363    248    201    150
    110     38  44646     29     44     42     72     49     75    121
    207    222    309    536    803    937   1047   1222   1375   1520
   1778   2101   2241   2409   2597   2835   2983   3035   3084   3318
   3327   3336   3359   3184   3043   2873   2727   2652   2340   2242
   2149   1923   1701   1509   1355   1283   1284   1195   1095   1029
    905    578    414    416    337    284    244    174     89     64
     24  86131     61     97    141    138    144    173    257    324
    457    473    567    676    701    760    870    953    939    994
   1005   1032   1082    983    971    875    860    837    672    602
    550    529    456    403    394    421    358    291    272    200
  26198     56    166    226    288    333    399    494    706    872
    922   1063   1324   1493   1645   1902   2135   2414   2695   2762
   2979   2996   3340   3334   3509   3756   3751   3780   3532   3470
   3159   2858   2731   2531   2382   2223   2006   1928   1648   1537
   1432   1339   1269   1149   1081    914    679    638    574    509
    426    401    318    213    135  92141     20     66    149    220
    277    307    362    387    454    568    722    885   1055   1085
   1158   1243   1299   1351   1437   1577   1326   1245   1206   1186
   1064   1035    940    871    814    671    668    617    581    514
    534    478    420    278    295    230    212    142    108     67
     50  36615     55     78     68    161    202    258    321    441
    566    659    853    981   1251   1434   1628   1917   2257   2412
   2743   3258   3573   4232   4668   5454   5608   5961   6362   6485
   7071   6934   7168   7365   7522   7337   6584   6175   5830   5186
   4867   4384   4122   3784   3406   3093   2758   2562   2317   2109
   1871   1869   1502   1038    930    779    726    587    476    304
    208    134     60     22 178298     43    154    176    249    328
    400    491    537    619    579    680    794    835    874    958
    942   1000    975   1046    889    781    685    614    504    419
    395    347    335    287    238    181    119    123     98     65
  24671     35     85    100     86    113    117    122    143    125
     63     52     40   3371    112    280    382    524    555    616
    790    833   1023   1121   1253   1453   1640   2233   2458   2680
   2837   3023   3062   3272   3452   3593   3658   3716   3325   3160
   3105   2931   2706   2457   2400   2179   1983   1879   1674   1569
   1323   1300   1207   1131   1061    952    626    575    447    435
    402    260    209    130  91658     91    147    234    343    427
    432    527    612    769    859    961   1097   1203   1308   1473
   1620   1590   1634   1753   1641   1666   1585   1599   1440   1348
   1199   1282   1204   1006   1059    834    817    737    663    522
    276    191    157    104  43490    153    243    296    330    405
    460    519    819    844    862    966    962   1014   1051    997
   1074   1024    984    865    836    734    696    654    606    573
    393    265  26311    162    273    440    525    629    792    901
   1050   1127   1275   1423   1536   1690   1685   1818   1886   1896
   1998   1982   1985   2016   1988   2000   1789   1809   1650   1297
   1298   1145    996    906    749    683    560    526    282    168
    120  54531    245    275    455    496    549    738    927   1058
   1278   1525   1723   1846   2052   2171   2271   2404   2650   2605
   2818   2906   2887   2679   2577   2375   2281   1908   1626   1523
   1400   1230   1071   1021    980    912    820    351    294    197
     90     83     26  70285    198    206    336    365    585    656
    774    725    828    816    752    603    523    434    385    344
    279    217    152     96     51  19066     70    253    274    361
    390    463    507    501    557    517    483    339    215  13978
    124     95     45    167    218    352    412    688    818    955
   1175   1305   1498   1632   2266   2488   2848   3039   3130   3524
   3392   3480   3594   3735   3740   3416   3166   2963   2563   2535
   2237   2005   1901   1656   1304   1214   1114   1048    929    745
    297    140  86398]

Colonna: vedovi
[     0      1      4      2      7      9     11     15     14     16
     12     26     18     32     22     34     33     58     45     62
     63     52     67     71     98    100    126    155    168    162
    183    190    197    225    246    268    274    329    350    320
    385    391    440    485    491    551    565    408    505    523
    569    608    673    670    683    661    574    559    495    421
    361    316    280    177    141    103  16330      6      3     13
     17     23     30     36     39     56     66     84     92     72
     87     91     97    101    131    149    143    157    169    165
    201    214    217    240    226    182    224    207    229    289
    297    302    285    278    231    244    212    203    127     70
     54     38     24   7208      5     20     35     43     53     88
    109    123    175    192    223    276    267    292    318    347
    353    424    381    486    544    517    583    627    711    714
    773    779    651    698    689    752    725    946    930    860
    866    836    812    685    702    538    417    369    245    210
    159    107     69  23166     48     47    106     85    133    151
    164    195    265    272    322    365    409    438    514    568
    713    887    919    957   1056   1109   1248   1271   1426   1514
   1619   1697   1705   1759   1947   2100   2213   2583   2617   2811
   2517   2214   2338   2405   2417   2711   2702   2473   2228   2094
   1907   1621   1445   1211    960    802    552    375    215    181
    116    184  70979     19     25     31     41     28     68    135
    186    200    222    239    252    295    411    423    468    516
    572    684    721    787    858    842    986   1031   1128   1157
   1282   1389   1496   1662   1951   2112   2281   1765   2056   2218
   2202   2399   2603   2772   2713   2523   2181   2198   2031   1387
   1202    977    703    498    397    242    145    253  61053     10
     50     46     61     76    102    110    152    185    178    237
    282    314    331    386    476    550    613    503    679    666
    677    808    863    762    727    600    571    462    414    346
    170    124     37  17201     40     57     86    105    119    132
    220    196    241    273    312    349    466    494    598    615
    730    810    769    896   1012   1077   1094   1269   1321   1480
   1503   1593   1617   1852   2105   2369   2608   2556   2168   2355
   2479   2581   2767   3156   3085   2822   2748   2432   2352   2095
   1659   1421   1259   1048    738    388    251    281  71602      8
     44     64     83     95    146    179    194    233    257    337
    396    457    460    504    620    774    843    750    856    874
   1061   1095   1137   1081    935    828    756    630    563    213
    137     77  23733     65     93    249    378    459    500    541
    573    628    726    783   1060   1070   1177   1214   1356   1488
   1626   1673   1827   1864   2196   2205   2478   2612   2779   2997
   3477   3795   4173   4348   4896   3871   4306   4528   4713   5066
   5793   5775   5719   4935   4321   4196   3606   2943   2628   2069
   1674   1154    581    248    305 127120     29     27     75     79
     90    108    118    154    176    199    232    341    392    433
    536    527    619    623    645    605    693    667    663    782
    862    879    678    710    657    548    410    293    238     82
  19649     42    129    128    147    113    120    160    171    115
   4053     21    114    142    259    291    371    464    512    621
    712    805    865    893   1021   1209   1291   1414   1473   1678
   1851   2129   2229   2411   1883   2232   2446   2457   2879   2915
   2828   2594   2342   2199   1905   1563   1333    650    425    299
  62895    125    173    343    333    465    567    596    747    770
    852    851    948   1017   1120   1115   1317   1350   1464   1740
   1811   1891   1722   1629   1731   1941   2133   2207   2071   1884
   1841   1721   1554   1351   1122    952    811    549    416    112
  51989    150    187    261    301    317    338    334    399    437
    482    471    518    526    634    618    687    695    723    682
    642    790    699    855    829    715    643    594    509    422
    368    279    243    161     73     81  20513     59    138    191
    230    483    490    641    674    724    823    956    966   1036
   1251   1349   1320   1405   1505   1842   2029   2096   2119   1914
   1877   2042   2025   2381   2348   2190   1969   1857   1835   1730
   1459   1156   1002    799    202    204  59004     78    188    256
    351    469    547    599    668    717    870    901    971   1042
   1091   1219   1309   1727   1858   2106   1752   1898   1879   2013
   2385   2395   2437   1983   1585   1437   1140   1011    791    625
    439    328    209  52908     49     74     96    227    254    362
    364    434    339    455    444    481    496    412    313    275
    269    104  11456    136    172    260    310    359    370    330
    477    493    535    553    484    389  11890     55     80   1671
    294    315    325    390    543    766    824    830    958   1101
   1217   1376   1489   1590   1753   1970   2098   2371   1793   2124
   2366   2396   2476   2716   2655   2540   2351   2012   1977   1770
   1413   1231    987    798    562    153  60789]

Colonna: uniti_civilmente
[   0    1    3    2    4    8    9    6   11   10    7   12    5  282
   35  145   14   18   19   17   23   27   28   26   20   24   31   25
   32   29   13   15 1015   16   33   47   45   46   51   60   40   63
   56   59   58   73   52   66   68   81   78   88   87   71   76   84
   67   57   44   39   36 2503   22  453   61   62   97   98   74   92
   86  115   94  111  105   95  118  117  122  114  116  129  128  124
  120   80   83   70   77   42   34 3989   21   30  763   55   89  141
  189  169  180  137  171  168  201  163  204  214  239  199  195  196
  191  185  203  194  184  156  147  148  134  108   91   69   38   43
 6818  439   53   72   50   90   64   37 2422  767  466 1074   41   49
   48 1636  437  341   65 2206]

Colonna: maschi_ex_unione_scioglimento
[  0   1   5   2   9   4   3  32   6  71  12   8   7  98  25  10  11  13
 221  97  18  37  62  20  70]

Colonna: maschi_ex_unione_decesso
[  0   1   3   2  11  48  12   4  47   5   8   6   7 165  58  16  31  41]

Colonna: totale_maschi
[   3821    3992    4239 ...     181     231 2392989]

Colonna: nubili
[  3553   3658   3919 ...     92    180 973508]

Colonna: coniugate
[      0       1       5 ...     108      70 1086346]

Colonna: divorziate
[     0      1      3      4      5     12     19     37     36     47
     78     96    124    137    173    221    261    287    306    374
    393    476    526    587    598    630    777    810    813    859
    861    892    926    911    902    850    907    798    702    679
    672    590    551    497    434    462    400    373    345    324
    276    248    217    185    145    141    110    101     94     64
     63     38     33     20     21     15     18      8      2  24859
     14     24     39     61     65     54     82     90    123    112
    130    150    158    208    229    216    204    254    252    233
    223    218    231    239    210    193    165    192    174    134
    128    114     92    105     74     84     69     67     73     49
     41     26     27     17     11     10     16      7      6   6529
     28     57     60     81     93    136    195    269    301    329
    370    437    442    473    536    576    639    686    701    682
    712    763    815    738    776    752    683    697    649    583
    539    574    491    496    457    436    395    355    305    281
    241    222    194    170    116    104     97     80     91     75
     31     34     23     13  22922     55    142    279    367    447
    571    593    694    789    917   1003   1112   1222   1330   1517
   1632   1697   1855   1985   2125   2143   2230   2292   2296   2270
   2418   2262   2269   2041   1865   1826   1649   1583   1488   1477
   1306   1242   1196    965    946    865    845    761    730    618
    563    430    343    298    247    230    198    154    161    125
     89     83     48      9  68418     40     52    138    171    270
    339    439    502    725    885   1012   1187   1321   1436   1513
   1779   1967   2172   2497   2749   3118   3329   3513   3755   3898
   4098   4213   4294   4190   4309   4252   4346   4018   3841   3605
   3636   3182   3048   2835   2679   2510   2297   2137   1764   1765
   1586   1403   1327    879    842    769    680    636    600    332
    169    139     58     25 121467     43     95    133    181    266
    322    404    427    500    506    668    792    886   1026   1074
   1059   1119   1234   1166   1229   1326   1353   1282   1338   1198
   1137   1117   1013   1015    896    873    805    760    719    602
    542    501    517    455    413    296    275    211    209    178
    157     77     29  36273     45     72    120    159    213    264
    334    443    603    976   1151   1304   1472   1701   1866   2278
   2452   2854   2991   3482   3799   3959   4228   4530   4770   4918
   4955   5202   5144   5168   5250   4897   4539   4199   4096   3848
   3641   3311   3179   2882   2799   2373   2390   2228   2181   1981
   1894   1756   1705   1254   1141   1121    981    891    622    456
    426    318     76     44     32 142000     35     88    111    147
    219    245    336    366    382    529    566    669    817    920
    980   1276   1333   1556   1577   1692   1757   1749   1827   1878
   1927   1944   1823   1708   1614   1500   1446   1346   1277   1228
   1099   1010    775    767    747    699    742    661    421    435
    347    319    323    283    160    152     22  51708     85    131
    162    240    335    523    693    912   1096   1597   1966   2327
   2569   2959   3243   3688   4093   4457   5187   5773   6177   7085
   7504   7940   8167   8348   8728   8999   8998   9059   9061   9007
   8717   8208   7449   6835   6521   6023   5424   5117   4759   4423
   4032   3702   3387   3159   2954   2879   2844   2575   2548   1641
   1587   1452   1396   1263   1180    937    874    634    346    246
    220    143 247954    121    187    190    250    303    316    398
    471    498    581    670    772    806    834    948   1045   1028
   1107   1182   1169   1214   1208   1204   1152   1202   1140   1091
   1016   1031    836    784    624    468    396    410    356    299
    289    226    183    135     42  33049     98    151    144    119
    140    166    148    109    107     79     30   4105    214    327
    467    512    573    732    903   1093   1297   1519   1679   1877
   2029   2328   2604   3028   3362   3639   3721   4136   4281   4510
   4589   4690   4640   4610   4631   4168   3952   3812   3565   3322
   3085   2874   2744   2504   2326   2083   1953   1800   1726   1578
   1593   1339    897    797    635    612    570    485    375    267
     99     51 127384     50    186    224    321    405    580    684
    883    978   1129   1224   1410   1575   1639   1776   1930   1978
   2023   1999   1988   1977   2082   1982   2002   1974   1848   1576
   1432   1322   1232   1168   1051   1007    864    868    716    688
    524    392    314    199    113    103  59451    342    377    460
    503    577    646    729    774    882    968    991   1097   1127
   1206   1160   1179   1210   1148   1150   1142   1004   1006    913
    843    827    710    652    535    585    533    458    414    340
    290    274    127    100     59     46  32506    117    191    308
    397    511    707    858    993   1065   1200   1310   1535   1626
   1792   1854   2068   2203   2337   2413   2473   2540   2559   2669
   2598   2511   2492   2427   2434   2151   2101   1962   1798   1561
   1542   1318   1302   1286   1019    944    987    803    781    737
    616    466    444    380    325    328    337    215    172    115
    106  75105    271    326    371    423    525    728    787    875
    972   1108   1299   1376   2141   2285   2605   2840   2985   3216
   3356   3351   3469   3439   3515   3611   3627   3722   3480   3116
   2988   2825   2644   2441   2295   2032   1917   1611   1371   1382
   1245   1260   1066    676    627    527    505    474    418  99029
     56     70    149    249    268    309    352    388    459    532
    620    687    783    866    960    928    967   1017    983    826
    835    818    723    642    586    518    431    255    176    163
     68  25851     66    108    167    175    243    300    359    433
    480    489    537    605    645    735    662    746    607    550
    575    490    470    403    311    272    242    203  19600    164
    155    126    118     87   4119     53     86    330    386    540
   1106   1233   1526   1643   2104   2455   2684   3055   3525   3787
   3924   4022   4298   4271   4293   4303   4299   4378   4332   3858
   3599   3507   3115   2800   2488   2416   2227   1889   1712   1492
   1418   1356   1191    997    623    647    486    384    320    253
    153     71 115521]

Colonna: vedove
[     0      2      1 ...   1310    879 283737]


In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/popolazione_regione.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/popolazione_regione.csv