In [1]:
import pandas as pd

df = pd.read_csv("../raw/1522_modalità_intervento.csv")

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,NATIONALITY,Nazionalità,OUTCOME_CALL,Esito della telefonata,TIME_PERIOD,Osservazione,OBS_STATUS
0,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2015.0,1337.0,NaN
1,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2016.0,1077.0,NaN
2,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2017.0,1093.0,NaN
3,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2018.0,864.0,NaN
4,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2019.0,874.0,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 249
Valori unici:
['A'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2021,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2023,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2020,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2021,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2023,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2024,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2015,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2021,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2023,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,ALL_VAL,Chiamate valide,2024,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,112_REQUIRED,Richiesto intervento del 112,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,113_REQUIRED,Richiesto  intervento 113,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,WORLD,Mondo,TOT_EMERG,Totale chiamate in emergenza,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2021,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2023,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TRANSF_SER,Trasferito servizio,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2020,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2021,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2023,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2024,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2015,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2021,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2023,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,ALL_VAL,Chiamate valide,2024,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,112_REQUIRED,Richiesto intervento del 112,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,113_REQUIRED,Richiesto  intervento 113,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,IT,Italia,TOT_EMERG,Totale chiamate in emergenza,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2015,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2016,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2017,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2018,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2019,8,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2020,20,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2022,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2023,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TRANSF_SER,Trasferito servizio,2024,40,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2016,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2019,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2020,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2021,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2022,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2023,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,NOTRANSF_SER,Non trasferito servizio,2024,20,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2015,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2016,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2017,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2018,19,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2019,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2020,25,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2021,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2022,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2023,30,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,ALL_VAL,Chiamate valide,2024,60,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,118_REQUIRED,Richiesto intervento del 118,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,112_REQUIRED,Richiesto intervento del 112,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,112_REQUIRED,Richiesto intervento del 112,2023,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,112_REQUIRED,Richiesto intervento del 112,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,113_REQUIRED,Richiesto  intervento 113,2023,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,113_REQUIRED,Richiesto  intervento 113,2024,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TOT_EMERG,Totale chiamate in emergenza,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TOT_EMERG,Totale chiamate in emergenza,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TOT_EMERG,Totale chiamate in emergenza,2023,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WORLD,Mondo,TOT_EMERG,Totale chiamate in emergenza,2024,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2015,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2016,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,TRANSF_SER,Trasferito servizio,2024,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,NOTRANSF_SER,Non trasferito servizio,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2015,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2016,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,WRL_X_ITA,Paesi esteri,ALL_VAL,Chiamate valide,2024,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2015,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2016,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2017,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2018,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2019,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2020,20,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2021,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2022,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2023,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,TRANSF_SER,Trasferito servizio,2024,34,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2016,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2019,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2020,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2021,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2022,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2023,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,NOTRANSF_SER,Non trasferito servizio,2024,20,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2015,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2016,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2017,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2018,18,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2019,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2020,25,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,IT,Italia,ALL_VAL,Chiamate valide,2021,12,,'

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",   
    "SEX", 
    "NATIONALITY", 
    "OUTCOME_CALL",     
    "OBS_STATUS" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (12733, 6)
Colonne rimanenti: ['Territorio', 'Sesso', 'Nazionalità', 'Esito della telefonata', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Nazionalità": "nazionalità_utente",
    "Esito della telefonata": "modalità_intervento",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: nazionalità_utente
['Mondo' 'Paesi esteri' 'Italia' 'Non Indicato']

Colonna: modalità_intervento
['Trasferito servizio' 'Non trasferito servizio' 'Chiamate valide'
 'Richiesto intervento del 118' 'Richiesto intervento del 112'
 'Richiesto  intervento 113' 'Totale chiamate in emergenza']

Colonna: periodo
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.]

Colonna: numero_vittime
[1337. 1077. 1093. ... 1182. 1294. 1366.]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige"
})


# Uniformazione minuscolo per sesso, nazionalità_utente, modalità_intervento
df["sesso"] = df["sesso"].astype(str).str.lower().str.strip()
df["modalità_intervento"] = df["modalità_intervento"].astype(str).str.lower().str.strip()
df["nazionalità_utente"] = df["nazionalità_utente"].astype(str).str.lower().str.strip()


# Nazionalità: mondo + paesi esteri -> esteri, e uniformazione non indicato
df["nazionalità_utente"] = df["nazionalità_utente"].replace({
    "mondo": "estero",
    "paesi esteri": "estero",
    "non indicato": "non indicato"
})


# Rimozione voci aggregate per evitare doppio conteggio
df = df[
    (df["sesso"] != "totale") &
    (df["modalità_intervento"] != "totale chiamate in emergenza")
]


# Rimozione doppio spazio e uniformazione
df["modalità_intervento"] = df["modalità_intervento"].replace({
    "richiesto  intervento 113": "richiesto intervento del 113"
})


# Conversione colonne numeriche (toglie i .0)
df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)


# Verifica finale post-pulizia (struttura + qualità base)
display(df.head(10))
df.info()

print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

for col in df.columns:
    print("\nColonna:", col)
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,territorio,sesso,nazionalità_utente,modalità_intervento,periodo,numero_vittime
0,italia,maschi,estero,trasferito servizio,2015,1337
1,italia,maschi,estero,trasferito servizio,2016,1077
2,italia,maschi,estero,trasferito servizio,2017,1093
3,italia,maschi,estero,trasferito servizio,2018,864
4,italia,maschi,estero,trasferito servizio,2019,874
5,italia,maschi,estero,trasferito servizio,2020,1197
6,italia,maschi,estero,trasferito servizio,2021,875
7,italia,maschi,estero,trasferito servizio,2022,667
8,italia,maschi,estero,trasferito servizio,2023,1717
9,italia,maschi,estero,trasferito servizio,2024,2573

<class 'pandas.core.frame.DataFrame'>
Index: 7083 entries, 0 to 12510
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   territorio           7083 non-null   object
 1   sesso                7083 non-null   object
 2   nazionalità_utente   7083 non-null   object
 3   modalità_intervento  7083 non-null   object
 4   periodo              7083 non-null   int64
 5   numero_vittime       7083 non-null   int64
dtypes: int64(2), object(4)
memory usage: 387.4+ KB

Missing values per colonna:

territorio             0
sesso                  0
nazionalità_utente     0
modalità_intervento    0
periodo                0
numero_vittime         0
dtype: int64

Numero valori unici per colonna:

numero_vittime         1413
territorio               26
periodo                  10
modalità_intervento       6
sesso                     3
nazionalità_utente        3
dtype: int64

Righe duplicate (identiche su tutte le colonne): 26

Colonna: territorio
['italia' 'nord ovest' 'piemonte' 'liguria' 'lombardia' 'nord est'
 'trentino alto adige' 'veneto' 'friuli venezia giulia' 'emilia romagna'
 'centro' 'toscana' 'umbria' 'marche' 'lazio' 'sud' 'abruzzo' 'molise'
 'campania' 'puglia' 'basilicata' 'calabria' 'isole' 'sicilia' 'sardegna'
 'non indicato']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: nazionalità_utente
['estero' 'italia' 'non indicato']

Colonna: modalità_intervento
['trasferito servizio' 'non trasferito servizio' 'chiamate valide'
 'richiesto intervento del 118' 'richiesto intervento del 112'
 'richiesto intervento del 113']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[1337 1077 1093 ... 1576 1458 2559]

In [6]:
# Numero righe prima
print("Righe prima:", len(df))

# Rimozione duplicati completi (tutte le colonne)
df = df.drop_duplicates()

# Numero righe dopo
print("Righe dopo:", len(df))

Righe prima: 7083
Righe dopo: 7057

In [7]:
# Salvataggio dataset pulito

output_path = "../data_clean/1522_modalità_intervento.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/1522_modalità_intervento.csv