Questa tabella è relativa solo all'anno 2018 e riporta la composizione percentuale (%) delle risposte di persone di nazionalità italiana e di età compresa fra i 18 e i 74 anni.

In [1]:
import pandas as pd

df = pd.read_csv(
    "../raw/Opinioni_violenza_sessuale_titolo_studio.csv",
    sep=";",
    encoding="utf-8-sig",
)

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,EDU_LEV_HIGHEST,Titolo di studio,STEREOT_GENDROLEPARTNER,"Stereotipi sui ruoli di genere, comportamenti nella coppia",DEGREE_AGREEMENT,Grado di accordo,TIME_PERIOD,Osservazione,OBS_STATUS
0,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",WPROVSEX,Le donne possono provocare la violenza sessual...,STRAGR,"'Molto d""'accordo'",2018,16.2,NaN
1,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",WPROVSEX,Le donne possono provocare la violenza sessual...,SOMAGR,"'Abbastanza d""'accordo'",2018,21.2,NaN
2,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",WPROVSEX,Le donne possono provocare la violenza sessual...,SOMDISAG,"'Poco d""'accordo'",2018,18.1,NaN
3,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",WPROVSEX,Le donne possono provocare la violenza sessual...,STRODIS,"'Per niente d""'accordo'",2018,27.7,NaN
4,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",WPROVSEX,Le donne possono provocare la violenza sessual...,NOANSW,Non risponde,2018,16.9,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 1
Valori unici:
['A']


============================================================
Colonna: Frequenza
Numero valori unici: 1
Valori unici:
['Annuale']


============================================================
Colonna: REF_AREA
Numero valori unici: 1
Valori unici:
['IT']


============================================================
Colonna: Territorio
Numero valori unici: 1
Valori unici:
['Italia']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 1
Valori unici:
['P18_74_AGVIOL']


============================================================
Colonna: Indicatore
Numero valori unici: 1
Valori unici:
['Persone di 18-74 anni per grado di accordo con alcuni stereotipi sulla violenza sessuale (composizione %)']


============================================================
Colonna: SEX
Numero valori unici: 3
Valori unici:
['M' 'F' 'T']


============================================================
Colonna: Sesso
Numero valori unici: 3
Valori unici:
['Maschi' 'Femmine' 'Totale']


============================================================
Colonna: EDU_LEV_HIGHEST
Numero valori unici: 5
Valori unici:
['NP' 'LSE' 'USE_IF' 'CLF_ML' 'ALL']


============================================================
Colonna: Titolo di studio
Numero valori unici: 5
Valori unici:
['Licenza di scuola elementare, nessun titolo di studio'
 'Licenza di scuola media inferiore o di avviamento professionale'
 'Diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS'
 'Laurea o diploma universitario' 'Totale']


============================================================
Colonna: STEREOT_GENDROLEPARTNER
Numero valori unici: 7
Valori unici:
['WPROVSEX' 'WABLAVO' 'SEWNRAP' 'HUSFNVIO' 'WOFSREM' 'WSVADRE' 'OACVIF']


============================================================
Colonna: Stereotipi sui ruoli di genere, comportamenti nella coppia
Numero valori unici: 7
Valori unici:
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']


============================================================
Colonna: DEGREE_AGREEMENT
Numero valori unici: 6
Valori unici:
['STRAGR' 'SOMAGR' 'SOMDISAG' 'STRODIS' 'NOANSW' 'TOT']


============================================================
Colonna: Grado di accordo
Numero valori unici: 6
Valori unici:
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 1
Valori unici:
[2018]


============================================================
Colonna: Osservazione
Numero valori unici: 303
Valori unici:
[ 16.2  21.2  18.1  27.7  16.9 100.   15.8  23.   19.   20.8  21.3   6.8
   7.7   9.1  57.2  19.2   1.8   2.2   3.4  74.4  18.3   5.4  10.8  15.6
  40.8  27.4   7.1  12.8  13.   48.5  18.5   4.5  11.4  24.3  35.1  24.6
   9.9  20.   21.7  42.4   6.1  15.4  27.9  24.1  23.8   8.9   3.9  74.6
   7.2   0.9   1.3   5.1  86.5  14.1  59.7  15.1   5.   13.1  11.6  62.9
   7.5   2.7  12.9  31.5  40.4  12.4  22.9  51.8   4.   13.8  29.   23.6
  27.1   6.4   1.4   3.7  78.6   4.7   0.8   5.8  88.    1.1   6.2  15.9
  64.5  12.2   3.2  13.5  65.6   5.3   1.6  10.1  33.5  43.2  11.5   9.3
  25.6  61.2  10.6  27.3  27.   30.8   4.3   0.4  83.9   2.1   0.1   1.
  92.4   2.    0.2   5.7  16.7  71.5   1.2   7.9  12.7  75.6   2.5   0.6
   7.   37.7  45.7   9.   16.8  22.6  48.3  14.   24.   26.1   8.   10.2
  76.5   5.2  87.2   1.7   7.4  62.3  13.3   3.8  12.   65.    6.5  10.7
  32.8  42.1  11.7  29.1  18.9  11.3  19.9  17.8   8.8  65.7  12.1  77.3
  12.6   3.   49.4  28.7  17.6  48.1  15.3   9.7  25.5  41.3  21.9   9.4
  20.6  19.6  44.8   5.6  26.2   9.6   2.4   4.1   6.3  81.   87.    5.9
  11.1  69.3  13.6  62.4  27.2  51.    5.5  14.5  20.1  57.    2.9  24.4
  31.6   0.7  86.3   0.3   3.5  92.    3.3  76.8   2.6  12.5  71.   31.8
  55.3   6.7   8.5  17.3  70.    8.2  20.7  89.9   2.3   3.6  94.   83.5
  78.9   0.5   4.8  28.3  60.3  17.1  19.3  52.1   4.6  25.3  25.4  30.1
   7.8   1.9   6.9  82.8   4.2  89.   11.8  72.3  10.5  12.3  66.9  53.1
  26.3  18.6  28.5  26.9  20.2  19.1   8.4  62.7  14.6   4.9  76.3  13.4
  46.3  16.4  10.3  25.1  39.1  20.3  43.5  14.2  24.9   9.2   7.6  77.7
   1.5  86.7   6.   64.3  13.7  29.5  45.5  21.5  54.3  26.8  29.3  82.3
  14.4  70.5  68.2  32.7  49.1  21.1  66.   23.7  27.5  36.   87.1  93.3
  78.   77.4  32.6  53.6  17.   20.9  50.2  26.6  24.7  28.1  79.7  88.1
  67.4  30.9  47.7]


============================================================
Colonna: OBS_STATUS
Numero valori unici: 1
Valori unici:
[nan]

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Territorio", 
    "Indicatore",        
    "SEX",                
    "EDU_LEV_HIGHEST",     
    "STEREOT_GENDROLEPARTNER",         
    "DEGREE_AGREEMENT" ,
    "OBS_STATUS",
    "TIME_PERIOD"
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (630, 5)
Colonne rimanenti: ['Sesso', 'Titolo di studio', 'Stereotipi sui ruoli di genere, comportamenti nella coppia', 'Grado di accordo', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Sesso": "sesso",
    "Titolo di studio": "titolo_studio",
    "Stereotipi sui ruoli di genere, comportamenti nella coppia": "imput_affermazione",
    "Grado di accordo": "grado_accordo",
    "Osservazione": "percentuale"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: sesso
['Maschi' 'Femmine' 'Totale']

Colonna: titolo_studio
['Licenza di scuola elementare, nessun titolo di studio'
 'Licenza di scuola media inferiore o di avviamento professionale'
 'Diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS'
 'Laurea o diploma universitario' 'Totale']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']

Colonna: percentuale
[ 16.2  21.2  18.1  27.7  16.9 100.   15.8  23.   19.   20.8  21.3   6.8
   7.7   9.1  57.2  19.2   1.8   2.2   3.4  74.4  18.3   5.4  10.8  15.6
  40.8  27.4   7.1  12.8  13.   48.5  18.5   4.5  11.4  24.3  35.1  24.6
   9.9  20.   21.7  42.4   6.1  15.4  27.9  24.1  23.8   8.9   3.9  74.6
   7.2   0.9   1.3   5.1  86.5  14.1  59.7  15.1   5.   13.1  11.6  62.9
   7.5   2.7  12.9  31.5  40.4  12.4  22.9  51.8   4.   13.8  29.   23.6
  27.1   6.4   1.4   3.7  78.6   4.7   0.8   5.8  88.    1.1   6.2  15.9
  64.5  12.2   3.2  13.5  65.6   5.3   1.6  10.1  33.5  43.2  11.5   9.3
  25.6  61.2  10.6  27.3  27.   30.8   4.3   0.4  83.9   2.1   0.1   1.
  92.4   2.    0.2   5.7  16.7  71.5   1.2   7.9  12.7  75.6   2.5   0.6
   7.   37.7  45.7   9.   16.8  22.6  48.3  14.   24.   26.1   8.   10.2
  76.5   5.2  87.2   1.7   7.4  62.3  13.3   3.8  12.   65.    6.5  10.7
  32.8  42.1  11.7  29.1  18.9  11.3  19.9  17.8   8.8  65.7  12.1  77.3
  12.6   3.   49.4  28.7  17.6  48.1  15.3   9.7  25.5  41.3  21.9   9.4
  20.6  19.6  44.8   5.6  26.2   9.6   2.4   4.1   6.3  81.   87.    5.9
  11.1  69.3  13.6  62.4  27.2  51.    5.5  14.5  20.1  57.    2.9  24.4
  31.6   0.7  86.3   0.3   3.5  92.    3.3  76.8   2.6  12.5  71.   31.8
  55.3   6.7   8.5  17.3  70.    8.2  20.7  89.9   2.3   3.6  94.   83.5
  78.9   0.5   4.8  28.3  60.3  17.1  19.3  52.1   4.6  25.3  25.4  30.1
   7.8   1.9   6.9  82.8   4.2  89.   11.8  72.3  10.5  12.3  66.9  53.1
  26.3  18.6  28.5  26.9  20.2  19.1   8.4  62.7  14.6   4.9  76.3  13.4
  46.3  16.4  10.3  25.1  39.1  20.3  43.5  14.2  24.9   9.2   7.6  77.7
   1.5  86.7   6.   64.3  13.7  29.5  45.5  21.5  54.3  26.8  29.3  82.3
  14.4  70.5  68.2  32.7  49.1  21.1  66.   23.7  27.5  36.   87.1  93.3
  78.   77.4  32.6  53.6  17.   20.9  50.2  26.6  24.7  28.1  79.7  88.1
  67.4  30.9  47.7]

In [5]:
# Pulizia valori categorici:
# - rimozione voci aggregate "Totale" da tutte le colonne testuali
# - normalizzazione label (sesso, titolo_studio, grado_accordo)
# - pulizia quote / caratteri sporchi
# - conversione percentuale a numerico


# Rimozione della voce aggregata "Totale" (ovunque) per evitare doppio conteggio

cat_cols = df.select_dtypes(include="object").columns

mask_totale = False
for c in cat_cols:
    mask_totale = mask_totale | (
        df[c].astype(str).str.strip().str.lower().eq("totale")
    )

print("Righe rimosse (contengono 'Totale'):", int(mask_totale.sum()))
df = df.loc[~mask_totale].copy()


# Uniformazione e pulizia valori per colonne chiave

# 1) sesso: minuscolo + standard
df["sesso"] = df["sesso"].str.lower().str.strip()

df["sesso"] = df["sesso"].replace({
    "maschi": "maschi",
    "femmine": "femmine"
})


# 2) titolo_studio: strip + accorciamento categorie
df["titolo_studio"] = df["titolo_studio"].str.strip()

df["titolo_studio"] = df["titolo_studio"].replace({
    "Licenza di scuola elementare, nessun titolo di studio": "elementare_o_nessun_titolo",
    "Licenza di scuola media inferiore o di avviamento professionale": "media_inferiore",
    "Diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS": "diploma_o_equivalente",
    "Laurea o diploma universitario": "laurea"
})


# 3) grado_accordo: rimozione quote sporche + normalizzazione
df["grado_accordo"] = (
    df["grado_accordo"].astype(str)
      .str.strip()
      .str.replace(r"^'+|'+$", "", regex=True)          # elimina apici esterni
      .str.replace('d"\'accordo', "d'accordo", regex=False)
      .str.replace('d"accordo', "d'accordo", regex=False)
      .str.replace('"', "", regex=False)
      .str.replace("\\", "", regex=False)
      .str.strip()
      .str.lower()
)

df["grado_accordo"] = df["grado_accordo"].replace({
    "molto d'accordo": "molto_d_accordo",
    "abbastanza d'accordo": "abbastanza_d_accordo",
    "poco d'accordo": "poco_d_accordo",
    "per niente d'accordo": "per_niente_d_accordo",
    "non risponde": "non_risponde"
})


# 4) imput_affermazione: pulizia base (testo)
df["imput_affermazione"] = df["imput_affermazione"].str.strip()


# 5) percentuale: conversione a numerico
df["percentuale"] = pd.to_numeric(df["percentuale"], errors="coerce")


# Verifica rapida post-pulizia (valori chiave)

print("\nNuova shape:", df.shape)

for col in ["sesso", "titolo_studio", "imput_affermazione", "grado_accordo"]:
    print("\nColonna:", col)
    print(df[col].unique())

Righe rimosse (contengono 'Totale'): 350

Nuova shape: (280, 5)

Colonna: sesso
['maschi' 'femmine']

Colonna: titolo_studio
['elementare_o_nessun_titolo' 'media_inferiore' 'diploma_o_equivalente'
 'laurea']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

In [6]:

# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,sesso,titolo_studio,imput_affermazione,grado_accordo,percentuale
0,maschi,elementare_o_nessun_titolo,Le donne possono provocare la violenza sessual...,molto_d_accordo,16.2
1,maschi,elementare_o_nessun_titolo,Le donne possono provocare la violenza sessual...,abbastanza_d_accordo,21.2
2,maschi,elementare_o_nessun_titolo,Le donne possono provocare la violenza sessual...,poco_d_accordo,18.1
3,maschi,elementare_o_nessun_titolo,Le donne possono provocare la violenza sessual...,per_niente_d_accordo,27.7
4,maschi,elementare_o_nessun_titolo,Le donne possono provocare la violenza sessual...,non_risponde,16.9
6,maschi,elementare_o_nessun_titolo,Le donne che non vogliono un rapporto sessuale...,molto_d_accordo,15.8
7,maschi,elementare_o_nessun_titolo,Le donne che non vogliono un rapporto sessuale...,abbastanza_d_accordo,23.0
8,maschi,elementare_o_nessun_titolo,Le donne che non vogliono un rapporto sessuale...,poco_d_accordo,19.0
9,maschi,elementare_o_nessun_titolo,Le donne che non vogliono un rapporto sessuale...,per_niente_d_accordo,20.8
10,maschi,elementare_o_nessun_titolo,Le donne che non vogliono un rapporto sessuale...,non_risponde,21.3

<class 'pandas.core.frame.DataFrame'>
Index: 280 entries, 0 to 376
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sesso               280 non-null    object
 1   titolo_studio       280 non-null    object
 2   imput_affermazione  280 non-null    object
 3   grado_accordo       280 non-null    object
 4   percentuale         280 non-null    float64
dtypes: float64(1), object(4)
memory usage: 13.1+ KB

Missing values per colonna:

sesso                 0
titolo_studio         0
imput_affermazione    0
grado_accordo         0
percentuale           0
dtype: int64

Numero valori unici per colonna:

percentuale           205
imput_affermazione      7
grado_accordo           5
titolo_studio           4
sesso                   2
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: sesso
['maschi' 'femmine']

Colonna: titolo_studio
['elementare_o_nessun_titolo' 'media_inferiore' 'diploma_o_equivalente'
 'laurea']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

Colonna: percentuale
[16.2 21.2 18.1 27.7 16.9 15.8 23.  19.  20.8 21.3  6.8  7.7  9.1 57.2
 19.2  1.8  2.2  3.4 74.4 18.3  5.4 10.8 15.6 40.8 27.4  7.1 12.8 13.
 48.5 18.5  4.5 11.4 24.3 35.1 24.6  9.9 20.  21.7 42.4  6.1 15.4 27.9
 24.1 23.8  8.9  3.9 74.6  7.2  0.9  1.3  5.1 86.5 14.1 59.7 15.1  5.
 13.1 11.6 62.9  7.5  2.7 12.9 31.5 40.4 12.4 22.9 51.8  4.  13.8 29.
 23.6 27.1  6.4  1.4  3.7 78.6  4.7  0.8  5.8 88.   1.1  6.2 15.9 64.5
 12.2  3.2 13.5 65.6  5.3  1.6 10.1 33.5 43.2 11.5  9.3 25.6 61.2 10.6
 27.3 27.  30.8  4.3  0.4 83.9  2.1  0.1  1.  92.4  2.   0.2  5.7 16.7
 71.5  1.2  7.9 12.7 75.6  2.5  0.6  7.  37.7 45.7  9.  11.7 29.1 18.9
 11.3 19.9 17.8  8.8 65.7 12.1 77.3 12.6  3.  49.4 28.7 17.6 48.1 15.3
  1.7  9.7 25.5 41.3 21.9  9.4 20.6 19.6 44.8  5.6 26.2  9.6  2.4  4.1
  6.3 81.  87.   5.9 11.1 69.3 13.6 62.4 27.2 51.   5.5 14.5 20.1 57.
  2.9 24.4 31.6  0.7 86.3  0.3  3.5 92.   3.3 76.8  6.5  2.6 10.2 12.5
 71.   3.8 31.8 55.3  6.7  8.5 17.3 70.   8.2 20.7 89.9  2.3  3.6 94.
 10.7 83.5  5.2 12.  78.9  0.5  4.8 28.3 60.3]

In [7]:
# Salvataggio dataset pulito

output_path = "../data_clean/Opinioni_violenza_sessuale_titolo_studio.csv"

df.to_csv(
    output_path,
    sep=",",
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/Opinioni_violenza_sessuale_titolo_studio.csv