Questa tabella è relativa solo all'anno 2018 e riporta la composizione percentuale (%) delle risposte di persone di nazionalità italiana e di età compresa fra i 18 e i 74 anni.

In [1]:
import pandas as pd

df = pd.read_csv(
    "../raw/Opinioni_violenza_sessuale_reg.csv",
    sep=";",
    encoding="utf-8-sig",
)

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,STEREOT_GENDROLEPARTNER,"Stereotipi sui ruoli di genere, comportamenti nella coppia",DEGREE_AGREEMENT,Grado di accordo,TIME_PERIOD,Osservazione,OBS_STATUS
0,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,WPROVSEX,Le donne possono provocare la violenza sessual...,STRAGR,"'Molto d""'accordo'",2018,7.0,NaN
1,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,WPROVSEX,Le donne possono provocare la violenza sessual...,SOMAGR,"'Abbastanza d""'accordo'",2018,16.8,NaN
2,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,WPROVSEX,Le donne possono provocare la violenza sessual...,SOMDISAG,"'Poco d""'accordo'",2018,22.6,NaN
3,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,WPROVSEX,Le donne possono provocare la violenza sessual...,STRODIS,"'Per niente d""'accordo'",2018,48.3,NaN
4,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,WPROVSEX,Le donne possono provocare la violenza sessual...,NOANSW,Non risponde,2018,5.3,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 1
Valori unici:
['A']


============================================================
Colonna: Frequenza
Numero valori unici: 1
Valori unici:
['Annuale']


============================================================
Colonna: REF_AREA
Numero valori unici: 28
Valori unici:
['IT' 'ITC' 'ITC1' 'ITC2' 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2']


============================================================
Colonna: Territorio
Numero valori unici: 28
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' '\'Valle d"\'Aosta / Vallée d"\'Aoste\''
 'Liguria' 'Lombardia' 'Nord-est' 'Trentino Alto Adige / Südtirol'
 'Provincia Autonoma Bolzano / Bozen' 'Provincia Autonoma Trento' 'Veneto'
 'Friuli-Venezia Giulia' 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria'
 'Marche' 'Lazio' 'Sud' 'Abruzzo' 'Molise' 'Campania' 'Puglia'
 'Basilicata' 'Calabria' 'Isole' 'Sicilia' 'Sardegna']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 1
Valori unici:
['P18_74_AGVIOL']


============================================================
Colonna: Indicatore
Numero valori unici: 1
Valori unici:
['Persone di 18-74 anni per grado di accordo con alcuni stereotipi sulla violenza sessuale (composizione %)']


============================================================
Colonna: SEX
Numero valori unici: 3
Valori unici:
['M' 'F' 'T']


============================================================
Colonna: Sesso
Numero valori unici: 3
Valori unici:
['Maschi' 'Femmine' 'Totale']


============================================================
Colonna: STEREOT_GENDROLEPARTNER
Numero valori unici: 7
Valori unici:
['WPROVSEX' 'WABLAVO' 'SEWNRAP' 'HUSFNVIO' 'WOFSREM' 'WSVADRE' 'OACVIF']


============================================================
Colonna: Stereotipi sui ruoli di genere, comportamenti nella coppia
Numero valori unici: 7
Valori unici:
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']


============================================================
Colonna: DEGREE_AGREEMENT
Numero valori unici: 6
Valori unici:
['STRAGR' 'SOMAGR' 'SOMDISAG' 'STRODIS' 'NOANSW' 'TOT']


============================================================
Colonna: Grado di accordo
Numero valori unici: 6
Valori unici:
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 1
Valori unici:
[2018]


============================================================
Colonna: Osservazione
Numero valori unici: 660
Valori unici:
[  7.   16.8  22.6  48.3   5.3 100.   14.   27.9  24.   26.1   8.    2.5
   4.7  10.2  76.5   6.2   0.8   1.1   5.2  87.2   5.7   1.7   7.4  15.4
  62.3  13.3   3.8  12.   12.7  65.    6.5   2.   10.7  32.8  42.1  12.4
   6.8  17.1  19.3  52.1   4.6  11.4  25.3  25.4  30.1   7.8   1.9   3.4
   6.9  82.8   5.    0.6   1.2   4.2  89.    4.3  11.8  72.3  10.5   3.2
  11.3  12.3  66.9   1.   29.   53.1   9.9  17.   20.9  50.2  26.6  24.7
  28.1   7.9   2.2   4.    8.5  79.7   5.6   0.7  88.1   1.4   5.8  13.6
  67.4   3.5  11.6  12.5  66.    6.4   1.5   8.8  30.9  47.7  11.1   3.9
  17.8  23.   51.   27.   25.5  29.2   6.7   0.9  10.4   4.8  88.4   4.4
   7.1  15.6  64.3   2.4  15.1  65.3  10.9  33.2  42.6  11.9  16.9  20.
  54.    9.   24.6  25.9  33.7   1.6   2.8  85.8   1.3  90.8   4.5  12.2
  74.    8.6   2.7  70.1   7.5  29.1  53.5   9.1  17.4  21.5  52.5   4.1
  10.3  25.8  25.7  31.4  89.6  13.9  69.2  12.1  67.7   5.1   9.2  31.1
  48.1  23.6  20.1  49.   30.5  26.5  83.    3.6   0.5   5.4  89.5   3.7
   7.2  19.1  61.7  11.   15.9  65.2  13.1  31.6  44.8  17.9  52.2   9.6
  25.1  36.3   6.   84.2   2.3  91.3  73.4   9.5  14.9  67.8   0.2  10.1
  27.2  53.2   9.3  20.7  19.6  50.6  26.7  31.5   7.3  83.6  90.5  15.5
  67.6  66.5  29.4   8.9  18.   51.7  30.6  22.1  22.5  82.    0.   89.3
   7.7  10.8  62.   17.7   2.1   8.1  13.2  43.9  15.8  27.6  44.6  30.4
  26.3  29.8   4.9  81.7  86.9   6.1  72.9  10.   13.7  68.4  31.    5.5
  22.8  24.2  26.2   3.3  81.9   0.4  67.5  12.8  12.6  68.8   6.3   9.7
  28.6  47.8  13.    1.8  14.6  18.6  54.6   8.4  19.2  28.3  33.1  64.9
  16.   16.3  35.3  36.5   2.9  10.6  21.9  59.5  31.8  32.4  88.5  92.2
  79.3  73.3  34.3  49.1  20.3  57.1  20.6  32.7  85.2  89.8  72.2  14.5
  70.5   7.6  34.8  42.9  25.   51.3  24.9  29.9  11.5  78.    0.3  65.4
  16.4  33.6  42.5  17.5  25.6  86.1   3.1  70.6  54.4  16.7  52.7  31.3
  82.1   5.9  69.4  13.4   8.3  48.5  24.1  49.2  27.7  20.2  74.7  86.6
   6.6  66.7  64.5  44.   11.7  18.5   3.   23.4  33.4  83.4  90.3  28.7
  55.2  21.6  50.9  21.8  79.1  70.4  11.2  30.   49.7  19.8  23.8  44.4
  16.5  25.2  68.9  82.9  14.2  64.8  62.4  24.8  38.6  18.3  46.1  28.
   8.2   2.6  79.   69.3  64.6  47.   19.7  22.   45.3   9.8  85.7  67.
  63.5  27.4  42.8  21.7  35.9  17.6  64.4  15.3  80.   61.5  17.3  64.7
  14.3  33.3  23.5  13.5  66.6   9.4  39.6  22.7  38.9  18.8  67.2  84.4
  63.8  27.1  36.2  19.5  51.9  29.6  72.8  85.4  15.2  13.8  60.4  43.1
  17.2  21.3  34.4  84.1  87.7  70.9  51.5  49.9  26.9  78.9  12.9  62.2
  47.6  23.1  27.8  32.2  74.1   8.7  84.7  65.8  44.3  21.1  21.2  81.2
  88.6  71.6  66.1  53.7  18.2  77.7  86.7  68.7  29.7  28.8  69.6  59.6
  35.   41.6  18.9  31.2  87.3  87.6  65.6  53.3  20.8  27.5  46.9  28.5
  78.5  62.7  47.5  14.8  24.3  78.3  68.6  45.8  57.2  38.3  93.3  70.2
  59.2  14.7  54.5  91.2  73.2  52.6  21.4  14.1  23.9  80.4  90.   63.3
  68.2  35.8  42.3  57.7  32.5  84.6  90.7  75.3  30.7  53.   55.7  82.5
  90.4  59.7  83.7  92.3  14.4  69.7  35.7  44.7  60.3  32.3  76.8  60.
  33.   83.3  91.8  71.9  49.3  73.   77.4  62.6  78.1  71.7  36.6  45.5
  24.4  77.6  89.1  72.6  74.5  43.8  22.3  46.2  38.   75.7  62.5  15.7
  43.6  16.2  46.7  78.8  86.2   0.1  22.9  46.4  22.4  77.3  87.8  64.2
  36.4  26.4  80.6  60.8  66.4  34.7  18.7  58.1  29.5  34.1  87.4  91.5
  76.3  72.4  30.2  53.8  55.3  69.5  48.9  42.   16.1  57.9  39.5  18.1
  19.9  46.3  28.2  79.2  85.9  44.2  75.9  84.8  63.2  19.4  35.4  88.3
  79.9  85.   42.2  40.5  76.9  40.   50.3  46.6  27.3  80.1  45.1  41.5
  26.   71.1  30.3  39.9  44.9  61.3  43.2  21.   75.1  15.   39.7  32.9
  69.9  81.6  58.8  58.   41.4  48.2  81.   87.1  74.4  63.4  56.4  23.7
  23.2  75.5  60.7  41.9  40.1  91.4  87.5  64.1  43.3  70.   89.4  59.3
  37.3  56.6  48.6  28.4  83.5  61.4  41.8  20.4  73.5  87.9  19.   48.8
  24.5  63.9  18.4  76.4  86.8  62.9  20.5  54.7  42.4  44.1  76.7  29.3
  74.6  60.5  30.8  77.   66.8  32.6  63.   86.4  88.7  77.2  58.2  72. ]


============================================================
Colonna: OBS_STATUS
Numero valori unici: 1
Valori unici:
[nan]

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",        
    "SEX",                     
    "STEREOT_GENDROLEPARTNER",         
    "DEGREE_AGREEMENT" ,
    "TIME_PERIOD",
    "OBS_STATUS"
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (3528, 5)
Colonne rimanenti: ['Territorio', 'Sesso', 'Stereotipi sui ruoli di genere, comportamenti nella coppia', 'Grado di accordo', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Stereotipi sui ruoli di genere, comportamenti nella coppia": "imput_affermazione",
    "Grado di accordo": "grado_accordo",
    "Osservazione": "percentuale"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' '\'Valle d"\'Aosta / Vallée d"\'Aoste\''
 'Liguria' 'Lombardia' 'Nord-est' 'Trentino Alto Adige / Südtirol'
 'Provincia Autonoma Bolzano / Bozen' 'Provincia Autonoma Trento' 'Veneto'
 'Friuli-Venezia Giulia' 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria'
 'Marche' 'Lazio' 'Sud' 'Abruzzo' 'Molise' 'Campania' 'Puglia'
 'Basilicata' 'Calabria' 'Isole' 'Sicilia' 'Sardegna']

Colonna: sesso
['Maschi' 'Femmine' 'Totale']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']

Colonna: percentuale
[  7.   16.8  22.6  48.3   5.3 100.   14.   27.9  24.   26.1   8.    2.5
   4.7  10.2  76.5   6.2   0.8   1.1   5.2  87.2   5.7   1.7   7.4  15.4
  62.3  13.3   3.8  12.   12.7  65.    6.5   2.   10.7  32.8  42.1  12.4
   6.8  17.1  19.3  52.1   4.6  11.4  25.3  25.4  30.1   7.8   1.9   3.4
   6.9  82.8   5.    0.6   1.2   4.2  89.    4.3  11.8  72.3  10.5   3.2
  11.3  12.3  66.9   1.   29.   53.1   9.9  17.   20.9  50.2  26.6  24.7
  28.1   7.9   2.2   4.    8.5  79.7   5.6   0.7  88.1   1.4   5.8  13.6
  67.4   3.5  11.6  12.5  66.    6.4   1.5   8.8  30.9  47.7  11.1   3.9
  17.8  23.   51.   27.   25.5  29.2   6.7   0.9  10.4   4.8  88.4   4.4
   7.1  15.6  64.3   2.4  15.1  65.3  10.9  33.2  42.6  11.9  16.9  20.
  54.    9.   24.6  25.9  33.7   1.6   2.8  85.8   1.3  90.8   4.5  12.2
  74.    8.6   2.7  70.1   7.5  29.1  53.5   9.1  17.4  21.5  52.5   4.1
  10.3  25.8  25.7  31.4  89.6  13.9  69.2  12.1  67.7   5.1   9.2  31.1
  48.1  23.6  20.1  49.   30.5  26.5  83.    3.6   0.5   5.4  89.5   3.7
   7.2  19.1  61.7  11.   15.9  65.2  13.1  31.6  44.8  17.9  52.2   9.6
  25.1  36.3   6.   84.2   2.3  91.3  73.4   9.5  14.9  67.8   0.2  10.1
  27.2  53.2   9.3  20.7  19.6  50.6  26.7  31.5   7.3  83.6  90.5  15.5
  67.6  66.5  29.4   8.9  18.   51.7  30.6  22.1  22.5  82.    0.   89.3
   7.7  10.8  62.   17.7   2.1   8.1  13.2  43.9  15.8  27.6  44.6  30.4
  26.3  29.8   4.9  81.7  86.9   6.1  72.9  10.   13.7  68.4  31.    5.5
  22.8  24.2  26.2   3.3  81.9   0.4  67.5  12.8  12.6  68.8   6.3   9.7
  28.6  47.8  13.    1.8  14.6  18.6  54.6   8.4  19.2  28.3  33.1  64.9
  16.   16.3  35.3  36.5   2.9  10.6  21.9  59.5  31.8  32.4  88.5  92.2
  79.3  73.3  34.3  49.1  20.3  57.1  20.6  32.7  85.2  89.8  72.2  14.5
  70.5   7.6  34.8  42.9  25.   51.3  24.9  29.9  11.5  78.    0.3  65.4
  16.4  33.6  42.5  17.5  25.6  86.1   3.1  70.6  54.4  16.7  52.7  31.3
  82.1   5.9  69.4  13.4   8.3  48.5  24.1  49.2  27.7  20.2  74.7  86.6
   6.6  66.7  64.5  44.   11.7  18.5   3.   23.4  33.4  83.4  90.3  28.7
  55.2  21.6  50.9  21.8  79.1  70.4  11.2  30.   49.7  19.8  23.8  44.4
  16.5  25.2  68.9  82.9  14.2  64.8  62.4  24.8  38.6  18.3  46.1  28.
   8.2   2.6  79.   69.3  64.6  47.   19.7  22.   45.3   9.8  85.7  67.
  63.5  27.4  42.8  21.7  35.9  17.6  64.4  15.3  80.   61.5  17.3  64.7
  14.3  33.3  23.5  13.5  66.6   9.4  39.6  22.7  38.9  18.8  67.2  84.4
  63.8  27.1  36.2  19.5  51.9  29.6  72.8  85.4  15.2  13.8  60.4  43.1
  17.2  21.3  34.4  84.1  87.7  70.9  51.5  49.9  26.9  78.9  12.9  62.2
  47.6  23.1  27.8  32.2  74.1   8.7  84.7  65.8  44.3  21.1  21.2  81.2
  88.6  71.6  66.1  53.7  18.2  77.7  86.7  68.7  29.7  28.8  69.6  59.6
  35.   41.6  18.9  31.2  87.3  87.6  65.6  53.3  20.8  27.5  46.9  28.5
  78.5  62.7  47.5  14.8  24.3  78.3  68.6  45.8  57.2  38.3  93.3  70.2
  59.2  14.7  54.5  91.2  73.2  52.6  21.4  14.1  23.9  80.4  90.   63.3
  68.2  35.8  42.3  57.7  32.5  84.6  90.7  75.3  30.7  53.   55.7  82.5
  90.4  59.7  83.7  92.3  14.4  69.7  35.7  44.7  60.3  32.3  76.8  60.
  33.   83.3  91.8  71.9  49.3  73.   77.4  62.6  78.1  71.7  36.6  45.5
  24.4  77.6  89.1  72.6  74.5  43.8  22.3  46.2  38.   75.7  62.5  15.7
  43.6  16.2  46.7  78.8  86.2   0.1  22.9  46.4  22.4  77.3  87.8  64.2
  36.4  26.4  80.6  60.8  66.4  34.7  18.7  58.1  29.5  34.1  87.4  91.5
  76.3  72.4  30.2  53.8  55.3  69.5  48.9  42.   16.1  57.9  39.5  18.1
  19.9  46.3  28.2  79.2  85.9  44.2  75.9  84.8  63.2  19.4  35.4  88.3
  79.9  85.   42.2  40.5  76.9  40.   50.3  46.6  27.3  80.1  45.1  41.5
  26.   71.1  30.3  39.9  44.9  61.3  43.2  21.   75.1  15.   39.7  32.9
  69.9  81.6  58.8  58.   41.4  48.2  81.   87.1  74.4  63.4  56.4  23.7
  23.2  75.5  60.7  41.9  40.1  91.4  87.5  64.1  43.3  70.   89.4  59.3
  37.3  56.6  48.6  28.4  83.5  61.4  41.8  20.4  73.5  87.9  19.   48.8
  24.5  63.9  18.4  76.4  86.8  62.9  20.5  54.7  42.4  44.1  76.7  29.3
  74.6  60.5  30.8  77.   66.8  32.6  63.   86.4  88.7  77.2  58.2  72. ]

In [5]:
# Pulizia valori categorici:
# - rimozione voci aggregate "Totale" da tutte le colonne testuali
# - normalizzazione label (sesso, territorio, grado_accordo)
# - pulizia quote / caratteri sporchi
# - conversione percentuale a numerico


# Rimozione della voce aggregata "Totale" (ovunque) per evitare doppio conteggio
cat_cols = df.select_dtypes(include="object").columns

mask_totale = False
for c in cat_cols:
    mask_totale = mask_totale | (
        df[c].astype(str).str.strip().str.lower().eq("totale")
    )

print("Righe rimosse (contengono 'Totale'):", int(mask_totale.sum()))
df = df.loc[~mask_totale].copy()


# 1) sesso: minuscolo + standard
df["sesso"] = df["sesso"].str.lower().str.strip()

df["sesso"] = df["sesso"].replace({
    "maschi": "maschi",
    "femmine": "femmine"
})


# 2) territorio: pulizia caratteri sporchi + minuscolo + correzione denominazioni
df["territorio"] = df["territorio"].str.strip()

df["territorio"] = df["territorio"].str.replace(r"^'+|'+$", "", regex=True)

df["territorio"] = df["territorio"].str.replace('"', "", regex=False)

df["territorio"] = df["territorio"].str.replace("\\", "", regex=False)

df["territorio"] = df["territorio"].str.lower().str.strip()

df["territorio"] = df["territorio"].str.replace("-", " ", regex=False)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige",
    "provincia autonoma bolzano / bozen": "bolzano",
    "provincia autonoma trento": "trento",
    "valle d'aosta / vallée d'aoste": "valle d'aosta"
})


# 3) grado_accordo: rimozione quote sporche + normalizzazione
df["grado_accordo"] = df["grado_accordo"].str.strip()

df["grado_accordo"] = df["grado_accordo"].str.replace(r"^'+|'+$", "", regex=True)

df["grado_accordo"] = df["grado_accordo"].str.replace('d"\'accordo', "d'accordo", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace('d"accordo', "d'accordo", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace('"', "", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace("\\", "", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.lower().str.strip()

df["grado_accordo"] = df["grado_accordo"].replace({
    "molto d'accordo": "molto_d_accordo",
    "abbastanza d'accordo": "abbastanza_d_accordo",
    "poco d'accordo": "poco_d_accordo",
    "per niente d'accordo": "per_niente_d_accordo",
    "non risponde": "non_risponde"
})


# 4) imput_affermazione: pulizia base
df["imput_affermazione"] = df["imput_affermazione"].str.strip()


# 5) percentuale: conversione a numerico
df["percentuale"] = pd.to_numeric(df["percentuale"], errors="coerce")


# Verifica rapida post-pulizia
print("\nNuova shape:", df.shape)

for col in ["territorio", "sesso", "imput_affermazione", "grado_accordo"]:
    print("\nColonna:", col)
    print(df[col].unique())

Righe rimosse (contengono 'Totale'): 1568

Nuova shape: (1960, 5)

Colonna: territorio
['italia' 'nord ovest' 'piemonte' "valle d'aosta" 'liguria' 'lombardia'
 'nord est' 'trentino alto adige' 'bolzano' 'trento' 'veneto'
 'friuli venezia giulia' 'emilia romagna' 'centro' 'toscana' 'umbria'
 'marche' 'lazio' 'sud' 'abruzzo' 'molise' 'campania' 'puglia'
 'basilicata' 'calabria' 'isole' 'sicilia' 'sardegna']

Colonna: sesso
['maschi' 'femmine']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

In [6]:

# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,territorio,sesso,imput_affermazione,grado_accordo,percentuale
0,italia,maschi,Le donne possono provocare la violenza sessual...,molto_d_accordo,7.0
1,italia,maschi,Le donne possono provocare la violenza sessual...,abbastanza_d_accordo,16.8
2,italia,maschi,Le donne possono provocare la violenza sessual...,poco_d_accordo,22.6
3,italia,maschi,Le donne possono provocare la violenza sessual...,per_niente_d_accordo,48.3
4,italia,maschi,Le donne possono provocare la violenza sessual...,non_risponde,5.3
6,italia,maschi,Le donne che non vogliono un rapporto sessuale...,molto_d_accordo,14.0
7,italia,maschi,Le donne che non vogliono un rapporto sessuale...,abbastanza_d_accordo,27.9
8,italia,maschi,Le donne che non vogliono un rapporto sessuale...,poco_d_accordo,24.0
9,italia,maschi,Le donne che non vogliono un rapporto sessuale...,per_niente_d_accordo,26.1
10,italia,maschi,Le donne che non vogliono un rapporto sessuale...,non_risponde,8.0

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 3484
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   territorio          1960 non-null   object
 1   sesso               1960 non-null   object
 2   imput_affermazione  1960 non-null   object
 3   grado_accordo       1960 non-null   object
 4   percentuale         1960 non-null   float64
dtypes: float64(1), object(4)
memory usage: 91.9+ KB

Missing values per colonna:

territorio            0
sesso                 0
imput_affermazione    0
grado_accordo         0
percentuale           0
dtype: int64

Numero valori unici per colonna:

percentuale           572
territorio             28
imput_affermazione      7
grado_accordo           5
sesso                   2
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' "valle d'aosta" 'liguria' 'lombardia'
 'nord est' 'trentino alto adige' 'bolzano' 'trento' 'veneto'
 'friuli venezia giulia' 'emilia romagna' 'centro' 'toscana' 'umbria'
 'marche' 'lazio' 'sud' 'abruzzo' 'molise' 'campania' 'puglia'
 'basilicata' 'calabria' 'isole' 'sicilia' 'sardegna']

Colonna: sesso
['maschi' 'femmine']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

Colonna: percentuale
[ 7.  16.8 22.6 48.3  5.3 14.  27.9 24.  26.1  8.   2.5  4.7 10.2 76.5
  6.2  0.8  1.1  5.2 87.2  5.7  1.7  7.4 15.4 62.3 13.3  3.8 12.  12.7
 65.   6.5  2.  10.7 32.8 42.1 12.4  6.8 17.1 19.3 52.1  4.6 11.4 25.3
 25.4 30.1  7.8  1.9  3.4  6.9 82.8  5.   0.6  1.2  4.2 89.   4.3 11.8
 72.3 10.5  3.2 11.3 12.3 66.9  1.  29.  53.1  9.9  3.9 17.8 23.  51.
 11.6 27.  25.5 29.2  6.7  0.9 10.4 79.7  4.8  0.7  5.6 88.4  4.4  7.1
 15.6 64.3 12.5  2.4 15.1 65.3  1.5 10.9 33.2 42.6 11.9 16.9 20.  54.
  9.  24.6 25.9 33.7  1.6  2.8 85.8  1.3 90.8  4.5 12.2 74.   8.6  2.7
 70.1  7.5 29.1 53.5  9.1  4.1 23.6 20.1 49.  30.5 26.5 83.   3.6  0.5
  5.4 89.5  3.7  7.2 19.1 61.7 11.  15.9  8.8 65.2 13.1 31.6 44.8  8.5
  6.4 17.9 52.2  9.6 25.1 36.3  6.   1.4 84.2  5.1  2.3 91.3  4.  73.4
  9.5  2.2 14.9 67.8  0.2 10.1 27.2 53.2  9.3 18.  51.7 30.6 22.1 22.5
 82.   0.  89.3  7.7 10.8 62.  17.7  2.1 69.2  8.1 13.2 43.9 15.8 27.6
 44.6 30.4 26.3 29.8  4.9 81.7 86.9  6.1 72.9  7.9  3.5 10.  13.7 68.4
 31.  10.3  1.8 14.6 18.6 54.6  8.4 19.2 28.3 33.1  8.9 12.1 64.9 16.
 16.3 67.5  0.4 35.3 36.5  2.9 10.6 21.9 59.5 31.8 32.4  7.3 88.5 92.2
 79.3 73.3 34.3 49.1 25.  51.3 26.6 24.9 29.9 11.5 78.   0.3 88.1 65.4
 16.4 33.6 42.5 17.5 25.6  5.8 86.1 90.5  3.1 11.1 70.6 54.4  5.9 24.1
 49.2 27.7 20.2 74.7 86.6  6.6 13.6 66.7 64.5 31.3 44.  11.7 18.5 52.7
  3.  23.4 33.4 83.4 90.3 28.7 55.2 19.8 23.8 44.4 16.5 25.2 68.9 82.9
 14.2 64.8  9.2 62.4 24.8 38.6 18.3 19.6 20.3 46.1 28.   8.2  2.6 79.
 69.3 64.6 30.  47.  12.8 21.7 35.9 29.4 17.6 64.4 15.3 80.  61.5 17.3
 64.7 14.3 33.3 23.5 12.6 13.5 89.8 66.6  9.4 66.  39.6 21.8 51.9 15.5
 29.6 72.8 85.4  7.6 15.2 67.7 13.8 60.4 43.1 16.7  9.7 17.2 21.3 34.4
 84.1 87.7 70.9 63.8  8.3 51.5 23.1 27.8 32.2 74.1  8.7 84.7 12.9 65.8
 44.3 21.1 50.6 21.2 81.2 88.6 13.4 71.6  9.8 66.1 53.7 22.8 28.8 13.9
 21.6 69.6  6.3 20.9 59.6 35.  41.6 18.9 26.2 49.9 20.7 31.2 87.3 87.6
 65.6 53.3 14.8 24.7 24.3 78.3 68.6 66.5 45.8 57.2 22.7 38.3 85.7 93.3
 77.7 70.2 59.2 21.4 14.1 26.7 23.9  3.3 80.4 90.  63.3 68.2  5.5 35.8
 42.3 57.7 32.5 84.6 90.7 75.3 30.7 53.  13.  59.7 83.7 92.3 14.4 69.7
 35.7 44.7 14.7 60.3 32.3 76.8 67.6 47.5 18.2 20.8 73.  77.4 62.6 82.1
 78.1 71.7 36.6 45.5 22.3 46.2 38.  27.1 75.7 62.5 15.7 43.6 16.2 46.7
 78.8 86.2  0.1 52.5 26.4 80.6 60.8 66.4 34.7 43.8 18.7 58.1 29.5 34.1
 87.4 91.5 76.3 72.4 30.2 53.8 42.  72.6 16.1 57.9 62.2 39.5 18.1 19.9
 46.3 28.2 79.2 85.9 19.4 35.4 34.8 22.9 88.3 62.7 33.  48.9 79.9 85.
 47.8 19.7 11.2 76.9 40.  28.1 83.3 24.2 50.3 41.5 26.  71.1 57.1 30.3
 39.9 19.5 44.9 78.9 61.3 39.7 32.9 22.4 69.9 81.6 58.8 58.  41.4 48.2
 81.  87.1 74.4 63.4 56.4 21.5 41.9 40.1 91.4 21.  73.2 87.5 67.2 64.1
 20.6 27.4 59.3 14.5 64.2 37.3 77.6 56.6 20.4 28.6 73.5 87.9 42.8 19.
 48.8 24.5 27.3 79.1 63.9 20.5 28.5 54.7 42.4 44.1 28.4 76.7 84.8 29.3
 50.9 29.7 77.  66.8 32.6 63.  31.5 86.4 88.7 75.5 77.2 48.5]

In [7]:
# Salvataggio dataset pulito

output_path = "../data_clean/Opinioni_violenza_sessuale_reg.csv"

df.to_csv(
    output_path,
    sep=",",
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/Opinioni_violenza_sessuale_reg.csv