Questa tabella è relativa solo all'anno 2018 e riporta la composizione percentuale (%) delle risposte di persone di nazionalità italiana e di età compresa fra i 18 e i 74 anni.

In [1]:
import pandas as pd

df = pd.read_csv(
    "../raw/Opinioni_violenza_sessuale_età.csv",
    sep=";",
    encoding="utf-8-sig",
)

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,AGE,Età,STEREOT_GENDROLEPARTNER,"Stereotipi sui ruoli di genere, comportamenti nella coppia",DEGREE_AGREEMENT,Grado di accordo,TIME_PERIOD,Osservazione,OBS_STATUS
0,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,Y18-29,18-29 anni,WPROVSEX,Le donne possono provocare la violenza sessual...,STRAGR,"'Molto d""'accordo'",2018,4.8,NaN
1,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,Y18-29,18-29 anni,WPROVSEX,Le donne possono provocare la violenza sessual...,SOMAGR,"'Abbastanza d""'accordo'",2018,10.1,NaN
2,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,Y18-29,18-29 anni,WPROVSEX,Le donne possono provocare la violenza sessual...,SOMDISAG,"'Poco d""'accordo'",2018,21.0,NaN
3,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,Y18-29,18-29 anni,WPROVSEX,Le donne possono provocare la violenza sessual...,STRODIS,"'Per niente d""'accordo'",2018,58.7,NaN
4,A,Annuale,IT,Italia,P18_74_AGVIOL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,Y18-29,18-29 anni,WPROVSEX,Le donne possono provocare la violenza sessual...,NOANSW,Non risponde,2018,5.4,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 1
Valori unici:
['A']


============================================================
Colonna: Frequenza
Numero valori unici: 1
Valori unici:
['Annuale']


============================================================
Colonna: REF_AREA
Numero valori unici: 28
Valori unici:
['IT' 'ITC' 'ITC1' 'ITC2' 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2']


============================================================
Colonna: Territorio
Numero valori unici: 28
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' '\'Valle d"\'Aosta / Vallée d"\'Aoste\''
 'Liguria' 'Lombardia' 'Nord-est' 'Trentino Alto Adige / Südtirol'
 'Provincia Autonoma Bolzano / Bozen' 'Provincia Autonoma Trento' 'Veneto'
 'Friuli-Venezia Giulia' 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria'
 'Marche' 'Lazio' 'Sud' 'Abruzzo' 'Molise' 'Campania' 'Puglia'
 'Basilicata' 'Calabria' 'Isole' 'Sicilia' 'Sardegna']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 1
Valori unici:
['P18_74_AGVIOL']


============================================================
Colonna: Indicatore
Numero valori unici: 1
Valori unici:
['Persone di 18-74 anni per grado di accordo con alcuni stereotipi sulla violenza sessuale (composizione %)']


============================================================
Colonna: SEX
Numero valori unici: 3
Valori unici:
['M' 'F' 'T']


============================================================
Colonna: Sesso
Numero valori unici: 3
Valori unici:
['Maschi' 'Femmine' 'Totale']


============================================================
Colonna: AGE
Numero valori unici: 5
Valori unici:
['Y18-29' 'Y30-44' 'Y45-59' 'Y60-74' 'TOTAL']


============================================================
Colonna: Età
Numero valori unici: 5
Valori unici:
['18-29 anni' '30-44 anni' '45-59 anni' '60-74 anni' 'Totale']


============================================================
Colonna: STEREOT_GENDROLEPARTNER
Numero valori unici: 7
Valori unici:
['WPROVSEX' 'WABLAVO' 'SEWNRAP' 'HUSFNVIO' 'WOFSREM' 'WSVADRE' 'OACVIF']


============================================================
Colonna: Stereotipi sui ruoli di genere, comportamenti nella coppia
Numero valori unici: 7
Valori unici:
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']


============================================================
Colonna: DEGREE_AGREEMENT
Numero valori unici: 6
Valori unici:
['STRAGR' 'SOMAGR' 'SOMDISAG' 'STRODIS' 'NOANSW' 'TOT']


============================================================
Colonna: Grado di accordo
Numero valori unici: 6
Valori unici:
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 1
Valori unici:
[2018]


============================================================
Colonna: Osservazione
Numero valori unici: 694
Valori unici:
[  4.8  10.1  21.   58.7   5.4 100.   14.9  26.5  28.3  24.    6.3   0.9
   5.6  15.6  72.    6.    0.6   1.1   7.1  85.6   1.    7.8  18.1  61.6
  11.5   2.7  13.   62.8   5.9   1.4  11.   36.   41.1  10.6  15.9  23.6
  51.2   3.1  29.1  24.9  28.1   4.9   1.9  10.2  81.3   3.4   0.7  89.6
   1.8   6.4  15.5  66.   10.3   4.4  12.2  65.9   4.5  10.5  32.9  43.2
  10.8   7.2  16.9  23.3  48.6   4.   14.3  28.7   7.3   2.8   4.2   8.3
  79.4   5.3   4.7  89.8   4.1   6.5  66.8  12.3  10.   10.9  70.9   9.6
  32.5  44.8  11.6   9.1  22.8  21.6  36.7   9.7  14.2  29.7  20.5  21.8
  13.8   3.9   8.5  70.4  82.1   2.5  16.6  52.   19.4   5.2  13.7  12.7
  57.4  30.9  37.7  16.7   7.   16.8  22.6  48.3  14.   27.9  26.1   8.
  76.5   6.2   0.8  87.2   5.7   1.7   7.4  15.4  62.3  13.3   3.8  12.
  65.    2.   10.7  32.8  42.1  12.4  10.4  65.3   3.3  11.3  21.1  32.3
   5.5   2.1  83.9   0.    4.6  91.5  13.2  79.2  14.1   0.2  31.4  56.8
   6.7   6.1  15.3  59.7   2.3  11.1  26.   25.3  33.3   5.8  88.4   2.6
  78.5  12.8  30.2  16.   20.8  51.5   4.3  11.8  25.6  24.7  30.7  83.
   5.    0.5   1.2  90.   73.7   9.4   3.    9.9  70.3   6.8  28.5  54.4
   9.3   7.9  22.4  36.5  26.7  23.8  24.4   3.7  76.1   8.7   2.2  83.5
  15.1  56.6   1.3   9.2  27.   45.3  17.2  17.1  19.3  52.1  11.4  25.4
  30.1   6.9  82.8  89.   72.3   3.2  66.9  29.   53.1   5.1  18.3  61.9
  23.9  28.   77.8   0.3  15.7  70.1  66.5  33.8  48.7  20.2  55.3  27.6
  25.1  30.6   8.1  84.8  90.5  13.4  72.1  12.9  68.1   8.4  31.6  49.9
  16.4  22.   50.1   3.6   7.7  89.9   2.9  70.6   8.2  30.4  49.8  36.6
   9.   22.2  23.2  73.4   9.5  56.   14.5  57.   11.2  28.8  41.7  17.
  20.9  50.2  26.6  79.7  88.1  13.6  67.4   3.5  12.5   1.5   8.8  47.7
  17.8  23.   51.   25.5  29.2  64.3   2.4  33.2  42.6  11.9  20.   54.
  24.6  25.9  33.7   1.6  85.8  90.8  74.    8.6   7.5  53.5  17.4  21.5
  52.5  25.8  25.7  13.9  69.2  12.1  67.7  31.1  48.1  20.1  49.   30.5
  89.5  19.1  61.7  65.2  13.1  17.9  52.2  36.3  84.2  91.3  67.8  27.2
  53.2  20.7  19.6  50.6  31.5  83.6  67.6  29.4   8.9  18.   51.7  22.1
  22.5  82.   89.3  62.   17.7  43.9  15.8  44.6  26.3  29.8  81.7  86.9
  72.9  68.4  31.   24.2  26.2  81.9   0.4  67.5  12.6  68.8  28.6  47.8
  14.6  18.6  54.6  19.2  33.1  64.9  16.3  35.3  21.9  59.5  31.8  32.4
  88.5  92.2  79.3  73.3  34.3  49.1  20.3  57.1  20.6  32.7  85.2  72.2
  70.5   7.6  34.8  42.9  25.   51.3  29.9  78.   65.4  33.6  42.5  17.5
  86.1  52.7  31.3  69.4  48.5  24.1  49.2  27.7  74.7  86.6   6.6  66.7
  64.5  44.   11.7  18.5  23.4  33.4  83.4  90.3  55.2  50.9  79.1  30.
  49.7  19.8  44.4  16.5  25.2  68.9  82.9  64.8  62.4  24.8  38.6  46.1
  79.   69.3  64.6  47.   19.7   9.8  85.7  67.   63.5  27.4  42.8  21.7
  35.9  17.6  64.4  80.   61.5  17.3  64.7  23.5  13.5  66.6  39.6  22.7
  38.9  18.8  67.2  84.4  63.8  27.1  36.2  19.5  51.9  29.6  72.8  85.4
  15.2  60.4  43.1  21.3  34.4  84.1  87.7  26.9  78.9  62.2  47.6  23.1
  27.8  32.2  74.1  84.7  65.8  44.3  21.2  81.2  88.6  71.6  66.1  53.7
  18.2  77.7  86.7  68.7  69.6  59.6  35.   41.6  18.9  31.2  87.3  87.6
  65.6  53.3  27.5  46.9  62.7  47.5  14.8  24.3  78.3  68.6  45.8  57.2
  38.3  93.3  70.2  59.2  14.7  54.5  91.2  73.2  52.6  21.4  80.4  63.3
  68.2  35.8  42.3  57.7  84.6  90.7  75.3  53.   55.7  82.5  90.4  83.7
  92.3  14.4  69.7  35.7  44.7  60.3  76.8  60.   33.   83.3  91.8  71.9
  49.3  73.   77.4  62.6  78.1  71.7  45.5  77.6  89.1  72.6  74.5  43.8
  22.3  46.2  38.   75.7  62.5  43.6  16.2  46.7  78.8  86.2   0.1  22.9
  46.4  77.3  87.8  64.2  36.4  26.4  80.6  60.8  66.4  34.7  18.7  58.1
  29.5  34.1  87.4  76.3  72.4  53.8  69.5  48.9  42.   16.1  57.9  39.5
  19.9  46.3  28.2  85.9  44.2  75.9  63.2  35.4  88.3  79.9  85.   42.2
  40.5  76.9  40.   50.3  46.6  27.3  80.1  45.1  41.5  71.1  30.3  39.9
  44.9  61.3  75.1  15.   39.7  69.9  81.6  58.8  58.   41.4  48.2  81.
  87.1  74.4  63.4  56.4  23.7  75.5  60.7  41.9  40.1  91.4  87.5  64.1
  43.3  70.   89.4  59.3  37.3  28.4  61.4  41.8  20.4  73.5  87.9  19.
  48.8  24.5  63.9  18.4  76.4  86.8  62.9  54.7  42.4  44.1  76.7  29.3
  74.6  60.5  30.8  77.   32.6  63.   86.4  88.7  77.2  58.2]


============================================================
Colonna: OBS_STATUS
Numero valori unici: 1
Valori unici:
[nan]

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE", 
    "Territorio",         
    "Indicatore",        
    "SEX",                     
    "AGE", 
    "STEREOT_GENDROLEPARTNER",        
    "DEGREE_AGREEMENT" ,
    "TIME_PERIOD",
    "OBS_STATUS"
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (4032, 5)
Colonne rimanenti: ['Sesso', 'Età', 'Stereotipi sui ruoli di genere, comportamenti nella coppia', 'Grado di accordo', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Sesso": "sesso",
    "Età": "età",
    "Stereotipi sui ruoli di genere, comportamenti nella coppia": "imput_affermazione",
    "Grado di accordo": "grado_accordo",
    "Osservazione": "percentuale"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: sesso
['Maschi' 'Femmine' 'Totale']

Colonna: età
['18-29 anni' '30-44 anni' '45-59 anni' '60-74 anni' 'Totale']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']

Colonna: percentuale
[  4.8  10.1  21.   58.7   5.4 100.   14.9  26.5  28.3  24.    6.3   0.9
   5.6  15.6  72.    6.    0.6   1.1   7.1  85.6   1.    7.8  18.1  61.6
  11.5   2.7  13.   62.8   5.9   1.4  11.   36.   41.1  10.6  15.9  23.6
  51.2   3.1  29.1  24.9  28.1   4.9   1.9  10.2  81.3   3.4   0.7  89.6
   1.8   6.4  15.5  66.   10.3   4.4  12.2  65.9   4.5  10.5  32.9  43.2
  10.8   7.2  16.9  23.3  48.6   4.   14.3  28.7   7.3   2.8   4.2   8.3
  79.4   5.3   4.7  89.8   4.1   6.5  66.8  12.3  10.   10.9  70.9   9.6
  32.5  44.8  11.6   9.1  22.8  21.6  36.7   9.7  14.2  29.7  20.5  21.8
  13.8   3.9   8.5  70.4  82.1   2.5  16.6  52.   19.4   5.2  13.7  12.7
  57.4  30.9  37.7  16.7   7.   16.8  22.6  48.3  14.   27.9  26.1   8.
  76.5   6.2   0.8  87.2   5.7   1.7   7.4  15.4  62.3  13.3   3.8  12.
  65.    2.   10.7  32.8  42.1  12.4  10.4  65.3   3.3  11.3  21.1  32.3
   5.5   2.1  83.9   0.    4.6  91.5  13.2  79.2  14.1   0.2  31.4  56.8
   6.7   6.1  15.3  59.7   2.3  11.1  26.   25.3  33.3   5.8  88.4   2.6
  78.5  12.8  30.2  16.   20.8  51.5   4.3  11.8  25.6  24.7  30.7  83.
   5.    0.5   1.2  90.   73.7   9.4   3.    9.9  70.3   6.8  28.5  54.4
   9.3   7.9  22.4  36.5  26.7  23.8  24.4   3.7  76.1   8.7   2.2  83.5
  15.1  56.6   1.3   9.2  27.   45.3  17.2  17.1  19.3  52.1  11.4  25.4
  30.1   6.9  82.8  89.   72.3   3.2  66.9  29.   53.1   5.1  18.3  61.9
  23.9  28.   77.8   0.3  15.7  70.1  66.5  33.8  48.7  20.2  55.3  27.6
  25.1  30.6   8.1  84.8  90.5  13.4  72.1  12.9  68.1   8.4  31.6  49.9
  16.4  22.   50.1   3.6   7.7  89.9   2.9  70.6   8.2  30.4  49.8  36.6
   9.   22.2  23.2  73.4   9.5  56.   14.5  57.   11.2  28.8  41.7  17.
  20.9  50.2  26.6  79.7  88.1  13.6  67.4   3.5  12.5   1.5   8.8  47.7
  17.8  23.   51.   25.5  29.2  64.3   2.4  33.2  42.6  11.9  20.   54.
  24.6  25.9  33.7   1.6  85.8  90.8  74.    8.6   7.5  53.5  17.4  21.5
  52.5  25.8  25.7  13.9  69.2  12.1  67.7  31.1  48.1  20.1  49.   30.5
  89.5  19.1  61.7  65.2  13.1  17.9  52.2  36.3  84.2  91.3  67.8  27.2
  53.2  20.7  19.6  50.6  31.5  83.6  67.6  29.4   8.9  18.   51.7  22.1
  22.5  82.   89.3  62.   17.7  43.9  15.8  44.6  26.3  29.8  81.7  86.9
  72.9  68.4  31.   24.2  26.2  81.9   0.4  67.5  12.6  68.8  28.6  47.8
  14.6  18.6  54.6  19.2  33.1  64.9  16.3  35.3  21.9  59.5  31.8  32.4
  88.5  92.2  79.3  73.3  34.3  49.1  20.3  57.1  20.6  32.7  85.2  72.2
  70.5   7.6  34.8  42.9  25.   51.3  29.9  78.   65.4  33.6  42.5  17.5
  86.1  52.7  31.3  69.4  48.5  24.1  49.2  27.7  74.7  86.6   6.6  66.7
  64.5  44.   11.7  18.5  23.4  33.4  83.4  90.3  55.2  50.9  79.1  30.
  49.7  19.8  44.4  16.5  25.2  68.9  82.9  64.8  62.4  24.8  38.6  46.1
  79.   69.3  64.6  47.   19.7   9.8  85.7  67.   63.5  27.4  42.8  21.7
  35.9  17.6  64.4  80.   61.5  17.3  64.7  23.5  13.5  66.6  39.6  22.7
  38.9  18.8  67.2  84.4  63.8  27.1  36.2  19.5  51.9  29.6  72.8  85.4
  15.2  60.4  43.1  21.3  34.4  84.1  87.7  26.9  78.9  62.2  47.6  23.1
  27.8  32.2  74.1  84.7  65.8  44.3  21.2  81.2  88.6  71.6  66.1  53.7
  18.2  77.7  86.7  68.7  69.6  59.6  35.   41.6  18.9  31.2  87.3  87.6
  65.6  53.3  27.5  46.9  62.7  47.5  14.8  24.3  78.3  68.6  45.8  57.2
  38.3  93.3  70.2  59.2  14.7  54.5  91.2  73.2  52.6  21.4  80.4  63.3
  68.2  35.8  42.3  57.7  84.6  90.7  75.3  53.   55.7  82.5  90.4  83.7
  92.3  14.4  69.7  35.7  44.7  60.3  76.8  60.   33.   83.3  91.8  71.9
  49.3  73.   77.4  62.6  78.1  71.7  45.5  77.6  89.1  72.6  74.5  43.8
  22.3  46.2  38.   75.7  62.5  43.6  16.2  46.7  78.8  86.2   0.1  22.9
  46.4  77.3  87.8  64.2  36.4  26.4  80.6  60.8  66.4  34.7  18.7  58.1
  29.5  34.1  87.4  76.3  72.4  53.8  69.5  48.9  42.   16.1  57.9  39.5
  19.9  46.3  28.2  85.9  44.2  75.9  63.2  35.4  88.3  79.9  85.   42.2
  40.5  76.9  40.   50.3  46.6  27.3  80.1  45.1  41.5  71.1  30.3  39.9
  44.9  61.3  75.1  15.   39.7  69.9  81.6  58.8  58.   41.4  48.2  81.
  87.1  74.4  63.4  56.4  23.7  75.5  60.7  41.9  40.1  91.4  87.5  64.1
  43.3  70.   89.4  59.3  37.3  28.4  61.4  41.8  20.4  73.5  87.9  19.
  48.8  24.5  63.9  18.4  76.4  86.8  62.9  54.7  42.4  44.1  76.7  29.3
  74.6  60.5  30.8  77.   32.6  63.   86.4  88.7  77.2  58.2]

In [5]:
# Pulizia valori categorici:
# - rimozione voci aggregate "Totale" dalle colonne rilevanti
# - normalizzazione label (sesso, età, grado_accordo)
# - pulizia quote / caratteri sporchi
# - conversione percentuale a numerico


# Rimozione della voce aggregata "Totale" solo nelle colonne utili all'analisi
mask_totale = (
    df["sesso"].astype(str).str.strip().str.lower().eq("totale")
    | df["età"].astype(str).str.strip().str.lower().eq("totale")
    | df["grado_accordo"].astype(str).str.strip().str.lower().eq("totale")
)

print("Righe rimosse (contengono 'Totale'):", int(mask_totale.sum()))
df = df.loc[~mask_totale].copy()


# 1) sesso: minuscolo + standard
df["sesso"] = df["sesso"].str.lower().str.strip()

df["sesso"] = df["sesso"].replace({
    "maschi": "maschi",
    "femmine": "femmine"
})


# 2) età: rimozione stringa "anni"
df["età"] = df["età"].str.strip()

df["età"] = df["età"].str.replace(" anni", "", regex=False)


# 3) grado_accordo: rimozione quote sporche + normalizzazione
df["grado_accordo"] = df["grado_accordo"].str.strip()

df["grado_accordo"] = df["grado_accordo"].str.replace(r"^'+|'+$", "", regex=True)

df["grado_accordo"] = df["grado_accordo"].str.replace('d"\'accordo', "d'accordo", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace('d"accordo', "d'accordo", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace('"', "", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace("\\", "", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.lower().str.strip()

df["grado_accordo"] = df["grado_accordo"].replace({
    "molto d'accordo": "molto_d_accordo",
    "abbastanza d'accordo": "abbastanza_d_accordo",
    "poco d'accordo": "poco_d_accordo",
    "per niente d'accordo": "per_niente_d_accordo",
    "non risponde": "non_risponde"
})


# 4) imput_affermazione: pulizia base
df["imput_affermazione"] = df["imput_affermazione"].str.strip()


# 5) percentuale: conversione a numerico
df["percentuale"] = pd.to_numeric(df["percentuale"], errors="coerce")



# Verifica rapida post-pulizia
print("\nNuova shape:", df.shape)

for col in ["sesso", "età", "imput_affermazione", "grado_accordo"]:
    print("\nColonna:", col)
    print(df[col].unique())

Righe rimosse (contengono 'Totale'): 3752

Nuova shape: (280, 5)

Colonna: sesso
['maschi' 'femmine']

Colonna: età
['18-29' '30-44' '45-59' '60-74']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

In [6]:

# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,sesso,età,imput_affermazione,grado_accordo,percentuale
0,maschi,18-29,Le donne possono provocare la violenza sessual...,molto_d_accordo,4.8
1,maschi,18-29,Le donne possono provocare la violenza sessual...,abbastanza_d_accordo,10.1
2,maschi,18-29,Le donne possono provocare la violenza sessual...,poco_d_accordo,21.0
3,maschi,18-29,Le donne possono provocare la violenza sessual...,per_niente_d_accordo,58.7
4,maschi,18-29,Le donne possono provocare la violenza sessual...,non_risponde,5.4
6,maschi,18-29,Le donne che non vogliono un rapporto sessuale...,molto_d_accordo,14.9
7,maschi,18-29,Le donne che non vogliono un rapporto sessuale...,abbastanza_d_accordo,26.5
8,maschi,18-29,Le donne che non vogliono un rapporto sessuale...,poco_d_accordo,28.3
9,maschi,18-29,Le donne che non vogliono un rapporto sessuale...,per_niente_d_accordo,24.0
10,maschi,18-29,Le donne che non vogliono un rapporto sessuale...,non_risponde,6.3

<class 'pandas.core.frame.DataFrame'>
Index: 280 entries, 0 to 376
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sesso               280 non-null    object
 1   età                 280 non-null    object
 2   imput_affermazione  280 non-null    object
 3   grado_accordo       280 non-null    object
 4   percentuale         280 non-null    float64
dtypes: float64(1), object(4)
memory usage: 13.1+ KB

Missing values per colonna:

sesso                 0
età                   0
imput_affermazione    0
grado_accordo         0
percentuale           0
dtype: int64

Numero valori unici per colonna:

percentuale           188
imput_affermazione      7
grado_accordo           5
età                     4
sesso                   2
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: sesso
['maschi' 'femmine']

Colonna: età
['18-29' '30-44' '45-59' '60-74']

Colonna: imput_affermazione
['Le donne possono provocare la violenza sessuale con il loro modo di vestire'
 'Le donne che non vogliono un rapporto sessuale riescono ad evitarlo'
 'Le donne serie non vengono violentate'
 'Se un marito/compagno obbliga la moglie/compagna ad avere un rapporto sessuale contro la sua volontà, non è una violenza'
 'Di fronte a una proposta sessuale le donne spesso dicono no ma in realtà intendono sì'
 'Se una donna subisce una violenza sessuale quando è ubriaca o è sotto l’effetto di droghe è almeno in parte responsabile'
 'Spesso le accuse di violenza sessuale sono false']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

Colonna: percentuale
[ 4.8 10.1 21.  58.7  5.4 14.9 26.5 28.3 24.   6.3  0.9  5.6 15.6 72.
  6.   0.6  1.1  7.1 85.6  1.   7.8 18.1 61.6 11.5  2.7 13.  62.8  5.9
  1.4 11.  36.  41.1 10.6 15.9 23.6 51.2  3.1 29.1 24.9 28.1  4.9  1.9
 10.2 81.3  3.4  0.7 89.6  1.8  6.4 15.5 66.  10.3  4.4 12.2 65.9  4.5
 10.5 32.9 43.2 10.8  7.2 16.9 23.3 48.6  4.  14.3 28.7  7.3  2.8  4.2
  8.3 79.4  5.3  4.7 89.8  4.1  6.5 66.8 12.3 10.  10.9 70.9  9.6 32.5
 44.8 11.6  9.1 22.8 21.6 36.7  9.7 14.2 29.7 20.5 21.8 13.8  3.9  8.5
 70.4 82.1  2.5 16.6 52.  19.4  5.2 13.7 12.7 57.4 30.9 37.7 16.7 10.4
 65.3  3.3 11.3 21.1 32.3  5.5  2.1 83.9  0.   4.6 91.5  0.8 13.2 79.2
 14.1  0.2 31.4 56.8  6.7  6.1 15.3 59.7  2.3 11.1 26.  25.3 33.3  5.8
 88.4  2.6 78.5 12.8  6.2 30.2  5.7 16.  20.8 51.5  4.3 11.8 25.6 24.7
 30.7 83.   5.   0.5  1.2 90.  73.7  9.4  3.   9.9 70.3  6.8 28.5 54.4
  9.3  7.9 22.4 36.5 26.7 23.8 24.4  3.7 76.1  8.7  2.2 83.5 12.  15.1
 56.6  1.3  9.2 27.  45.3 17.2]

In [7]:
# Salvataggio dataset pulito

output_path = "../data_clean/Opinioni_violenza_sessuale_età.csv"

df.to_csv(
    output_path,
    sep=",",
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/Opinioni_violenza_sessuale_età.csv