Questa tabella è relativa solo all'anno 2018 e riporta la composizione percentuale (%) delle risposte di persone di nazionalità italiana e di età compresa fra i 18 e i 74 anni.

In [1]:
import pandas as pd

df = pd.read_csv(
    "../raw/Opinioni_ruoli_tradizionali_titolo_studio.csv",
    sep=";",
    encoding="utf-8-sig",
)

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,EDU_LEV_HIGHEST,Titolo di studio,STEREOT_GENDROLEPARTNER,"Stereotipi sui ruoli di genere, comportamenti nella coppia",DEGREE_AGREEMENT,Grado di accordo,TIME_PERIOD,Osservazione,OBS_STATUS
0,A,Annuale,IT,Italia,P18_74_AGROL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",PRIOMEN,"In condizioni di scarsità di lavoro,i datori d...",STRAGR,"'Molto d""'accordo'",2018,19.5,NaN
1,A,Annuale,IT,Italia,P18_74_AGROL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",PRIOMEN,"In condizioni di scarsità di lavoro,i datori d...",SOMAGR,"'Abbastanza d""'accordo'",2018,26.0,NaN
2,A,Annuale,IT,Italia,P18_74_AGROL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",PRIOMEN,"In condizioni di scarsità di lavoro,i datori d...",SOMDISAG,"'Poco d""'accordo'",2018,9.2,NaN
3,A,Annuale,IT,Italia,P18_74_AGROL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",PRIOMEN,"In condizioni di scarsità di lavoro,i datori d...",STRODIS,"'Per niente d""'accordo'",2018,41.3,NaN
4,A,Annuale,IT,Italia,P18_74_AGROL,Persone di 18-74 anni per grado di accordo con...,M,Maschi,NP,"Licenza di scuola elementare, nessun titolo di...",PRIOMEN,"In condizioni di scarsità di lavoro,i datori d...",NOANSW,Non risponde,2018,4.0,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 1
Valori unici:
['A']


============================================================
Colonna: Frequenza
Numero valori unici: 1
Valori unici:
['Annuale']


============================================================
Colonna: REF_AREA
Numero valori unici: 1
Valori unici:
['IT']


============================================================
Colonna: Territorio
Numero valori unici: 1
Valori unici:
['Italia']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 1
Valori unici:
['P18_74_AGROL']


============================================================
Colonna: Indicatore
Numero valori unici: 1
Valori unici:
['Persone di 18-74 anni per grado di accordo con alcuni stereotipi sui ruoli tradizionali di genere (composizione %)']


============================================================
Colonna: SEX
Numero valori unici: 3
Valori unici:
['M' 'F' 'T']


============================================================
Colonna: Sesso
Numero valori unici: 3
Valori unici:
['Maschi' 'Femmine' 'Totale']


============================================================
Colonna: EDU_LEV_HIGHEST
Numero valori unici: 5
Valori unici:
['NP' 'LSE' 'USE_IF' 'CLF_ML' 'ALL']


============================================================
Colonna: Titolo di studio
Numero valori unici: 5
Valori unici:
['Licenza di scuola elementare, nessun titolo di studio'
 'Licenza di scuola media inferiore o di avviamento professionale'
 'Diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS'
 'Laurea o diploma universitario' 'Totale']


============================================================
Colonna: STEREOT_GENDROLEPARTNER
Numero valori unici: 5
Valori unici:
['PRIOMEN' 'MPRFAM' 'MTAKEDE' 'MLESHOUS' 'MISUCWOR']


============================================================
Colonna: Stereotipi sui ruoli di genere, comportamenti nella coppia
Numero valori unici: 5
Valori unici:
['In condizioni di scarsità di lavoro,i datori di lavoro dovrebbero dare la precedenza agli uomini rispetto alle donne'
 '\'È soprattutto l"\'uomo che deve provvedere alle necessità economiche della famiglia\''
 '\'È l"\'uomo che deve prendere le decisioni più importanti riguardanti la famiglia\''
 'Gli uomini sono meno adatti ad occuparsi delle faccende domestiche'
 'Per l’uomo,più che per la donna,è molto importante avere successo nel lavoro']


============================================================
Colonna: DEGREE_AGREEMENT
Numero valori unici: 6
Valori unici:
['STRAGR' 'SOMAGR' 'SOMDISAG' 'STRODIS' 'NOANSW' 'TOT']


============================================================
Colonna: Grado di accordo
Numero valori unici: 6
Valori unici:
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 1
Valori unici:
[2018]


============================================================
Colonna: Osservazione
Numero valori unici: 242
Valori unici:
[ 19.5  26.    9.2  41.3   4.  100.   31.5  34.5   7.5  24.8   1.7  18.8
  12.2  12.9  53.7   2.4  25.2  26.7  16.7  28.7   2.7  24.6  25.   13.6
  31.6   5.2   6.2  13.2  14.   65.8   0.8  16.2  25.4  14.9  43.    0.5
   5.4   7.7  12.7  73.8   0.4  12.4  22.1  20.6  44.3   0.6  11.   20.9
  50.8   1.    3.4   8.2  14.1   7.6  16.6  19.7  55.7   2.5  76.6   8.
  19.1  23.8  48.5   7.   20.3  18.3  53.6   3.1  11.4  84.3   2.3  10.9
  19.2  67.3   0.3   0.9   2.6  85.2   3.3  18.6  21.   56.7   4.9  21.6
  17.3  55.2   5.1  10.4  13.3  70.4  20.   17.1  50.9   4.4   6.3  13.4
  75.4  10.   21.8  47.    0.7   9.3  51.4   1.2  11.5  22.   11.1  53.4
   2.   28.9  13.5  36.7   1.4   8.8  11.7  68.6   1.6  34.4  15.4  27.8
   1.8  17.4  27.9  39.3  14.8  16.4  61.8  10.2  22.3  17.2  49.7   6.1
  11.6  78.5  13.9  23.9  42.2  12.1  14.7   2.9   9.5  76.2   4.5  62.3
  86.9   9.   18.9  52.5   8.7  16.   52.1   1.3   5.6   8.3  84.6   0.2
   7.3  72.4   0.1  91.7   3.7  25.8  57.8  17.9  50.2   4.7  12.   70.5
  17.   17.8  57.1   4.6   9.6  82.9  21.3  19.8  47.3  24.3  15.3  48.6
  14.3  23.5  49.   30.9  11.3  32.5   1.5  12.3  11.9  10.6  63.3   1.9
  22.2  15.9  28.2   2.1  26.9  36.6  15.2  63.9  46.2  76.   13.1  23.
  19.9  43.3  22.8  15.5   1.1   8.9  12.6  75.   15.1  58.9   4.1  81.6
   8.5  21.4  50.4   7.8  52.9   9.7  84.4  70.   88.7   3.5  23.6  57.3
   5.5  17.6  11.2   9.4  18.5  17.5  54.1  79.2  10.5  20.8  47.1   9.8
  22.7  50. ]


============================================================
Colonna: OBS_STATUS
Numero valori unici: 1
Valori unici:
[nan]

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Territorio", 
    "Indicatore",        
    "SEX",                
    "EDU_LEV_HIGHEST",     
    "STEREOT_GENDROLEPARTNER",         
    "DEGREE_AGREEMENT" ,
    "OBS_STATUS",
    "TIME_PERIOD"
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (450, 5)
Colonne rimanenti: ['Sesso', 'Titolo di studio', 'Stereotipi sui ruoli di genere, comportamenti nella coppia', 'Grado di accordo', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Sesso": "sesso",
    "Titolo di studio": "titolo_studio",
    "Stereotipi sui ruoli di genere, comportamenti nella coppia": "imput_affermazione",
    "Grado di accordo": "grado_accordo",
    "Osservazione": "percentuale"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: sesso
['Maschi' 'Femmine' 'Totale']

Colonna: titolo_studio
['Licenza di scuola elementare, nessun titolo di studio'
 'Licenza di scuola media inferiore o di avviamento professionale'
 'Diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS'
 'Laurea o diploma universitario' 'Totale']

Colonna: imput_affermazione
['In condizioni di scarsità di lavoro,i datori di lavoro dovrebbero dare la precedenza agli uomini rispetto alle donne'
 '\'È soprattutto l"\'uomo che deve provvedere alle necessità economiche della famiglia\''
 '\'È l"\'uomo che deve prendere le decisioni più importanti riguardanti la famiglia\''
 'Gli uomini sono meno adatti ad occuparsi delle faccende domestiche'
 'Per l’uomo,più che per la donna,è molto importante avere successo nel lavoro']

Colonna: grado_accordo
['\'Molto d"\'accordo\'' '\'Abbastanza d"\'accordo\''
 '\'Poco d"\'accordo\'' '\'Per niente d"\'accordo\'' 'Non risponde'
 'Totale']

Colonna: percentuale
[ 19.5  26.    9.2  41.3   4.  100.   31.5  34.5   7.5  24.8   1.7  18.8
  12.2  12.9  53.7   2.4  25.2  26.7  16.7  28.7   2.7  24.6  25.   13.6
  31.6   5.2   6.2  13.2  14.   65.8   0.8  16.2  25.4  14.9  43.    0.5
   5.4   7.7  12.7  73.8   0.4  12.4  22.1  20.6  44.3   0.6  11.   20.9
  50.8   1.    3.4   8.2  14.1   7.6  16.6  19.7  55.7   2.5  76.6   8.
  19.1  23.8  48.5   7.   20.3  18.3  53.6   3.1  11.4  84.3   2.3  10.9
  19.2  67.3   0.3   0.9   2.6  85.2   3.3  18.6  21.   56.7   4.9  21.6
  17.3  55.2   5.1  10.4  13.3  70.4  20.   17.1  50.9   4.4   6.3  13.4
  75.4  10.   21.8  47.    0.7   9.3  51.4   1.2  11.5  22.   11.1  53.4
   2.   28.9  13.5  36.7   1.4   8.8  11.7  68.6   1.6  34.4  15.4  27.8
   1.8  17.4  27.9  39.3  14.8  16.4  61.8  10.2  22.3  17.2  49.7   6.1
  11.6  78.5  13.9  23.9  42.2  12.1  14.7   2.9   9.5  76.2   4.5  62.3
  86.9   9.   18.9  52.5   8.7  16.   52.1   1.3   5.6   8.3  84.6   0.2
   7.3  72.4   0.1  91.7   3.7  25.8  57.8  17.9  50.2   4.7  12.   70.5
  17.   17.8  57.1   4.6   9.6  82.9  21.3  19.8  47.3  24.3  15.3  48.6
  14.3  23.5  49.   30.9  11.3  32.5   1.5  12.3  11.9  10.6  63.3   1.9
  22.2  15.9  28.2   2.1  26.9  36.6  15.2  63.9  46.2  76.   13.1  23.
  19.9  43.3  22.8  15.5   1.1   8.9  12.6  75.   15.1  58.9   4.1  81.6
   8.5  21.4  50.4   7.8  52.9   9.7  84.4  70.   88.7   3.5  23.6  57.3
   5.5  17.6  11.2   9.4  18.5  17.5  54.1  79.2  10.5  20.8  47.1   9.8
  22.7  50. ]

In [5]:
# Pulizia valori categorici:
# - rimozione voci aggregate "Totale" da tutte le colonne testuali
# - normalizzazione label (sesso, titolo_studio, grado_accordo)
# - pulizia quote / caratteri sporchi
# - pulizia testi in imput_affermazione
# - conversione percentuale a numerico


# Rimozione della voce aggregata "Totale" (ovunque) per evitare doppio conteggio
cat_cols = df.select_dtypes(include="object").columns

mask_totale = False
for c in cat_cols:
    mask_totale = mask_totale | (
        df[c].astype(str).str.strip().str.lower().eq("totale")
    )

print("Righe rimosse (contengono 'Totale'):", int(mask_totale.sum()))
df = df.loc[~mask_totale].copy()


# Uniformazione e pulizia valori per colonne chiave

# 1) sesso: minuscolo + standard
df["sesso"] = df["sesso"].str.lower().str.strip()

df["sesso"] = df["sesso"].replace({
    "maschi": "maschi",
    "femmine": "femmine"
})


# 2) titolo_studio: strip + accorciamento categorie
df["titolo_studio"] = df["titolo_studio"].str.strip()

df["titolo_studio"] = df["titolo_studio"].replace({
    "Licenza di scuola elementare, nessun titolo di studio": "elementare_o_nessun_titolo",
    "Licenza di scuola media inferiore o di avviamento professionale": "media_inferiore",
    "Diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS": "diploma_o_equivalente",
    "Laurea o diploma universitario": "laurea"
})


# 3) grado_accordo: rimozione quote sporche + normalizzazione
df["grado_accordo"] = df["grado_accordo"].astype(str).str.strip()

df["grado_accordo"] = df["grado_accordo"].str.replace(r"^'+|'+$", "", regex=True)

df["grado_accordo"] = df["grado_accordo"].str.replace('d"\'accordo', "d'accordo", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace('d"accordo', "d'accordo", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace('"', "", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.replace("\\", "", regex=False)

df["grado_accordo"] = df["grado_accordo"].str.strip().str.lower()

df["grado_accordo"] = df["grado_accordo"].replace({
    "molto d'accordo": "molto_d_accordo",
    "abbastanza d'accordo": "abbastanza_d_accordo",
    "poco d'accordo": "poco_d_accordo",
    "per niente d'accordo": "per_niente_d_accordo",
    "non risponde": "non_risponde"
})


# 4) imput_affermazione: pulizia testi
df["imput_affermazione"] = df["imput_affermazione"].str.strip()

df["imput_affermazione"] = df["imput_affermazione"].str.replace(r"^'+|'+$", "", regex=True)

df["imput_affermazione"] = df["imput_affermazione"].str.replace('l"\'uomo', "l'uomo", regex=False)

df["imput_affermazione"] = df["imput_affermazione"].str.replace('L"\'uomo', "L'uomo", regex=False)

df["imput_affermazione"] = df["imput_affermazione"].str.replace('"', "", regex=False)

df["imput_affermazione"] = df["imput_affermazione"].str.replace("\\", "", regex=False)

df["imput_affermazione"] = df["imput_affermazione"].str.replace(r"\s*,\s*", ", ", regex=True)

df["imput_affermazione"] = df["imput_affermazione"].str.replace(r"\s+", " ", regex=True)

df["imput_affermazione"] = df["imput_affermazione"].str.strip()


# 5) percentuale: conversione a numerico
df["percentuale"] = pd.to_numeric(df["percentuale"], errors="coerce")


# Verifica rapida post-pulizia (valori chiave)
print("\nNuova shape:", df.shape)

for col in ["sesso", "titolo_studio", "imput_affermazione", "grado_accordo"]:
    print("\nColonna:", col)
    print(df[col].unique())

Righe rimosse (contengono 'Totale'): 250

Nuova shape: (200, 5)

Colonna: sesso
['maschi' 'femmine']

Colonna: titolo_studio
['elementare_o_nessun_titolo' 'media_inferiore' 'diploma_o_equivalente'
 'laurea']

Colonna: imput_affermazione
['In condizioni di scarsità di lavoro, i datori di lavoro dovrebbero dare la precedenza agli uomini rispetto alle donne'
 "È soprattutto l'uomo che deve provvedere alle necessità economiche della famiglia"
 "È l'uomo che deve prendere le decisioni più importanti riguardanti la famiglia"
 'Gli uomini sono meno adatti ad occuparsi delle faccende domestiche'
 'Per l’uomo, più che per la donna, è molto importante avere successo nel lavoro']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

In [6]:

# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,sesso,titolo_studio,imput_affermazione,grado_accordo,percentuale
0,maschi,elementare_o_nessun_titolo,"In condizioni di scarsità di lavoro, i datori ...",molto_d_accordo,19.5
1,maschi,elementare_o_nessun_titolo,"In condizioni di scarsità di lavoro, i datori ...",abbastanza_d_accordo,26.0
2,maschi,elementare_o_nessun_titolo,"In condizioni di scarsità di lavoro, i datori ...",poco_d_accordo,9.2
3,maschi,elementare_o_nessun_titolo,"In condizioni di scarsità di lavoro, i datori ...",per_niente_d_accordo,41.3
4,maschi,elementare_o_nessun_titolo,"In condizioni di scarsità di lavoro, i datori ...",non_risponde,4.0
6,maschi,elementare_o_nessun_titolo,È soprattutto l'uomo che deve provvedere alle ...,molto_d_accordo,31.5
7,maschi,elementare_o_nessun_titolo,È soprattutto l'uomo che deve provvedere alle ...,abbastanza_d_accordo,34.5
8,maschi,elementare_o_nessun_titolo,È soprattutto l'uomo che deve provvedere alle ...,poco_d_accordo,7.5
9,maschi,elementare_o_nessun_titolo,È soprattutto l'uomo che deve provvedere alle ...,per_niente_d_accordo,24.8
10,maschi,elementare_o_nessun_titolo,È soprattutto l'uomo che deve provvedere alle ...,non_risponde,1.7

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 268
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sesso               200 non-null    object
 1   titolo_studio       200 non-null    object
 2   imput_affermazione  200 non-null    object
 3   grado_accordo       200 non-null    object
 4   percentuale         200 non-null    float64
dtypes: float64(1), object(4)
memory usage: 9.4+ KB

Missing values per colonna:

sesso                 0
titolo_studio         0
imput_affermazione    0
grado_accordo         0
percentuale           0
dtype: int64

Numero valori unici per colonna:

percentuale           152
grado_accordo           5
imput_affermazione      5
titolo_studio           4
sesso                   2
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: sesso
['maschi' 'femmine']

Colonna: titolo_studio
['elementare_o_nessun_titolo' 'media_inferiore' 'diploma_o_equivalente'
 'laurea']

Colonna: imput_affermazione
['In condizioni di scarsità di lavoro, i datori di lavoro dovrebbero dare la precedenza agli uomini rispetto alle donne'
 "È soprattutto l'uomo che deve provvedere alle necessità economiche della famiglia"
 "È l'uomo che deve prendere le decisioni più importanti riguardanti la famiglia"
 'Gli uomini sono meno adatti ad occuparsi delle faccende domestiche'
 'Per l’uomo, più che per la donna, è molto importante avere successo nel lavoro']

Colonna: grado_accordo
['molto_d_accordo' 'abbastanza_d_accordo' 'poco_d_accordo'
 'per_niente_d_accordo' 'non_risponde']

Colonna: percentuale
[19.5 26.   9.2 41.3  4.  31.5 34.5  7.5 24.8  1.7 18.8 12.2 12.9 53.7
  2.4 25.2 26.7 16.7 28.7  2.7 24.6 25.  13.6 31.6  5.2  6.2 13.2 14.
 65.8  0.8 16.2 25.4 14.9 43.   0.5  5.4  7.7 12.7 73.8  0.4 12.4 22.1
 20.6 44.3  0.6 11.  20.9 50.8  1.   3.4  8.2 14.1  7.6 16.6 19.7 55.7
  2.5 76.6  8.  19.1 23.8 48.5  7.  20.3 18.3 53.6  3.1 11.4 84.3  2.3
 10.9 19.2 67.3  0.3  0.9  2.6 85.2  3.3 18.6 21.  56.7  4.9 21.6 17.3
 55.2 11.5 22.  11.1 53.4  2.  28.9 13.5 36.7  1.4  8.8 11.7  9.3 68.6
  1.6 34.4 15.4 27.8  1.8 17.4 27.9 39.3  4.4  6.3 14.8 16.4 61.8 10.2
 22.3 17.2 49.7  6.1 11.6 78.5 13.9 23.9 42.2  0.7 12.1 14.7 47.   1.2
  2.9  9.5 76.2  4.5 62.3 86.9  9.  18.9 52.5  8.7 16.  52.1  1.3  5.6
  8.3 84.6  0.2  7.3 72.4  0.1 91.7  3.7 25.8 57.8 17.9 50.2]

In [7]:
# Salvataggio dataset pulito

output_path = "../data_clean/Opinioni_ruoli_tradizionali_titolo_studio.csv"

df.to_csv(
    output_path,
    sep=",",
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/Opinioni_ruoli_tradizionali_titolo_studio.csv